/* ─────────────────────────────────────────────────────────────
   BLOG DATA — NRI Tax Knowledge Hub
   ───────────────────────────────────────────────────────────── */

export const CATEGORIES = [
  { id: 'all', label: 'All', icon: '📚' },
  { id: 'guide', label: 'Guides', icon: '📖' },
  { id: 'tax', label: 'Tax', icon: '💰' },
  { id: 'compliance', label: 'Compliance', icon: '⚖️' },
  { id: 'investment', label: 'Investment', icon: '📈' },
  { id: 'banking', label: 'Banking', icon: '🏦' },
  { id: 'assessment', label: 'Self-Assessment', icon: '✅' },
];

export const TOPICS = [
  { id: 'all', label: 'All Guides', icon: '📚' },
  { id: 'property', label: 'Property & Capital Gains', icon: '🏠', desc: 'Selling, buying, rental income, Section 54' },
  { id: 'country', label: 'Country Guides', icon: '🌍', desc: 'US, UK, UAE, Singapore, Canada, Australia, Germany' },
  { id: 'filing', label: 'ITR Filing & TDS', icon: '📋', desc: 'Forms, deadlines, TDS rates, refunds' },
  { id: 'income', label: 'Income & Deductions', icon: '💰', desc: 'Salary, ESOP, pension, 80C/80D, NPS' },
  { id: 'banking', label: 'Banking & FEMA', icon: '🏦', desc: 'NRE/NRO, repatriation, 15CA/15CB' },
  { id: 'planning', label: 'Planning & Strategy', icon: '📊', desc: 'Tax saving, investments, retirement' },
  { id: 'compliance', label: 'Notices & Compliance', icon: '⚖️', desc: 'Notices, ITR-U, AIS, Schedule FA' },
];

export const BLOGS = [
  {
    slug: 'nri-property-sale-capital-gains',
    title: 'NRI Property Sale & Capital Gains Tax',
    subtitle: 'The Definitive 2026 Guide',
    excerpt: 'Dual tax options (20% indexed vs 12.5% flat), TDS under Section 195, Section 54/54EC exemptions, and complete repatriation guide with Form 15CA/CB.',
    category: 'guide',
    topic: 'property',
    tags: ['Property Sale', 'Capital Gains', 'TDS', 'Section 54'],
    readTime: '15 min',
    featured: true,
    views: '789K+ source views',
    icon: '🏠',
    color: '#2A6B4A',
    keyNumbers: [
      { label: 'CII 2025-26', value: '376' },
      { label: 'LTCG Rate', value: '12.5%' },
      { label: 'TDS Rate', value: '20%' },
      { label: 'Sec 54 Cap', value: '₹10Cr' },
    ],
    quickAnswer: 'When an NRI sells property in India, the buyer deducts TDS at 20% of the entire sale price under Section 195. For pre-July 2024 acquisitions, NRIs choose between 20% with indexation or 12.5% flat rate — whichever gives lower tax.',
  },
  {
    slug: 'nri-tax-filing-itr',
    title: 'NRI Income Tax Filing in India',
    subtitle: 'Complete ITR Guide for AY 2026-27',
    excerpt: 'Step-by-step guide covering ITR form selection, new vs old regime, Section 87A (not for NRIs!), TDS refund claims, AIS reconciliation, and 10 common mistakes.',
    category: 'guide',
    topic: 'filing',
    tags: ['ITR Filing', 'Tax Return', 'AY 2026-27', 'New Regime'],
    readTime: '12 min',
    featured: true,
    views: '5.7M+ source views',
    icon: '📋',
    color: '#B07D3A',
    keyNumbers: [
      { label: 'Due Date', value: '31 Jul 2026' },
      { label: 'ITR Form', value: 'ITR-2' },
      { label: 'Exemption', value: '₹4L' },
      { label: 'Sec 87A', value: 'NOT for NRI' },
    ],
    quickAnswer: 'Most NRIs must file ITR-2 in India if income exceeds ₹4 lakh (new regime). The new tax regime is default — NRIs cannot claim Section 87A rebate. Filing is essential to claim TDS refunds, which are often ₹2-5 lakh for property sales.',
  },
  {
    slug: 'nri-tds-rates-refund',
    title: 'TDS on NRI Income in India',
    subtitle: 'Rates, Refund & Section 197 Certificate',
    excerpt: 'Complete TDS rate chart for NRIs — property sale (20%), NRO interest (30%), dividends (20%). How to apply for Section 197 lower TDS certificate and claim refunds.',
    category: 'tax',
    topic: 'filing',
    tags: ['TDS', 'Section 195', 'Section 197', 'Refund'],
    readTime: '18 min',
    featured: false,
    views: '1.07M+ source views',
    icon: '🧾',
    color: '#A04848',
    keyNumbers: [
      { label: 'Property TDS', value: '20%' },
      { label: 'NRO Interest', value: '30%' },
      { label: 'Dividend TDS', value: '20%' },
      { label: 'Rent TDS', value: '30%' },
    ],
    quickAnswer: 'NRI TDS rates are significantly higher than resident rates — 30% on NRO interest, 20% on property sale, 20% on dividends. Apply for Section 197 lower TDS certificate to bring deduction in line with actual tax liability.',
  },
  {
    slug: 'nre-nro-fcnr-banking',
    title: 'NRE vs NRO vs FCNR Accounts',
    subtitle: 'NRI Banking Guide 2026',
    excerpt: 'Tax-free NRE interest, NRO taxation at 30%, FCNR currency protection. The 3-account strategy every NRI needs, FEMA conversion rules, and repatriation limits.',
    category: 'banking',
    topic: 'banking',
    tags: ['NRE', 'NRO', 'FCNR', 'Banking'],
    readTime: '14 min',
    featured: false,
    views: '3.28M+ source views',
    icon: '🏦',
    color: '#2E5E8C',
    keyNumbers: [
      { label: 'NRE Interest', value: 'Tax-Free' },
      { label: 'NRO TDS', value: '30%' },
      { label: 'Repatriation', value: 'USD 1M/yr' },
      { label: 'FCNR', value: 'FX Protected' },
    ],
    quickAnswer: 'NRE accounts hold foreign earnings with tax-free interest and full repatriation. NRO accounts hold Indian income with 30% TDS and USD 1M/year repatriation limit. FCNR deposits protect against currency risk with tax-free interest.',
  },
  {
    slug: 'dtaa-double-taxation-ftc',
    title: 'DTAA for NRIs',
    subtitle: 'Avoid Double Taxation with Foreign Tax Credit',
    excerpt: 'India\'s treaties with US, UK, UAE, Canada, Singapore, Australia. Country-specific rates, Form 67 (mandatory!), TRC requirements, and practical examples.',
    category: 'tax', topic: 'country',
    tags: ['DTAA', 'FTC', 'Form 67', 'TRC'],
    readTime: '16 min',
    featured: false,
    views: '113K+ source views',
    icon: '🌐',
    color: '#5B21B6',
    keyNumbers: [
      { label: 'US Interest', value: '15%' },
      { label: 'UAE Interest', value: '12.5%' },
      { label: 'Form 67', value: 'Mandatory' },
      { label: 'Countries', value: '90+' },
    ],
    quickAnswer: 'India has DTAAs with 90+ countries that cap withholding rates on interest (10-15% vs domestic 20%), dividends, and royalties. Claiming Foreign Tax Credit requires mandatory Form 67 filing before ITR due date — non-filing means FTC denied.',
  },
  {
    slug: 'fema-compliance-nri',
    title: 'FEMA Compliance for NRIs',
    subtitle: 'Rules, Penalties & Common Mistakes',
    excerpt: 'Bank account conversion, property purchase rules, ED penalties (up to 3x), Form 15CA/15CB, LRS limits, and the 2026 Foreign Assets Disclosure Scheme.',
    category: 'compliance', topic: 'banking',
    tags: ['FEMA', 'RBI', 'Penalties', 'Form 15CA'],
    readTime: '15 min',
    featured: true,
    views: '4.73M+ source views',
    icon: '⚖️',
    color: '#DC2626',
    keyNumbers: [
      { label: 'LRS Limit', value: 'USD 250K' },
      { label: 'NRO Repatriation', value: 'USD 1M' },
      { label: 'ED Penalty', value: 'Up to 3x' },
      { label: 'Disclosure', value: '6-month window' },
    ],
    quickAnswer: 'FEMA violations carry penalties up to 3 times the amount involved. Common violations: keeping resident savings account after becoming NRI, unauthorized property ownership, exceeding LRS limits. Budget 2026 introduced a 6-month disclosure window.',
  },
  {
    slug: 'nri-investment-mutual-funds',
    title: 'NRI Investment in India',
    subtitle: 'Mutual Funds, Stocks & SIP Guide 2026',
    excerpt: 'Equity MF (12.5% LTCG), debt MF, SIP from NRE/NRO, PIS for stocks, GIFT City zero-tax, ESOP lifecycle, crypto 30%, and Budget 2026 changes.',
    category: 'investment', topic: 'planning',
    tags: ['Mutual Funds', 'Stocks', 'SIP', 'GIFT City'],
    readTime: '18 min',
    featured: false,
    views: '6.42M+ source views',
    icon: '📈',
    color: '#059669',
    keyNumbers: [
      { label: 'Equity LTCG', value: '12.5%' },
      { label: 'STCG', value: '20%' },
      { label: 'GIFT City', value: '0% Tax' },
      { label: 'Crypto', value: '30% Flat' },
    ],
    quickAnswer: 'NRIs can invest in Indian mutual funds via NRE/NRO accounts after KYC. Equity LTCG taxed at 12.5% above ₹1.25L, STCG at 20%. GIFT City funds offer zero-tax alternative. Budget 2026 increased NRI stock holding limit to 10%.',
  },
  {
    slug: 'gift-city-nri-investment',
    title: 'GIFT City for NRIs',
    subtitle: 'Tax-Free Investing in India 2026',
    excerpt: 'Zero capital gains tax, zero STT, zero dividend tax through India\'s International Financial Services Centre. AIF funds, FDs, and NSE IX exchange.',
    category: 'investment', topic: 'planning',
    tags: ['GIFT City', 'IFSC', 'Zero Tax', 'AIF'],
    readTime: '10 min',
    featured: false,
    views: '63K+ source views',
    icon: '🏛️',
    color: '#7C3AED',
    keyNumbers: [
      { label: 'Capital Gains', value: '0%' },
      { label: 'Dividend Tax', value: '0%' },
      { label: 'STT', value: '0%' },
      { label: 'Min Investment', value: '~USD 150K' },
    ],
    quickAnswer: 'GIFT City IFSC funds offer NRIs zero capital gains tax, zero dividend tax, and zero STT on India investments. Denominated in USD with minimum ~USD 150K. Regulated by IFSCA with strong investor protection.',
  },
  {
    slug: 'nri-rental-income-house-property',
    title: 'NRI Rental Income Tax in India',
    subtitle: 'House Property Guide 2026',
    excerpt: '30% standard deduction, home loan interest (Section 24), deemed let-out property, TDS on rent, loss set-off rules, and municipal tax treatment.',
    category: 'tax', topic: 'property',
    tags: ['Rental Income', 'House Property', 'Section 24', 'TDS'],
    readTime: '10 min',
    featured: false,
    views: '386K+ source views',
    icon: '🏢',
    color: '#B45309',
    keyNumbers: [
      { label: 'Std Deduction', value: '30%' },
      { label: 'TDS on Rent', value: '30%' },
      { label: 'Loss Set-off', value: '₹2L' },
      { label: 'Loan Interest', value: 'No Cap (Let-out)' },
    ],
    quickAnswer: 'NRI rental income is taxed after 30% standard deduction. Home loan interest is fully deductible for let-out property (no cap). TDS at 30% is deducted by tenant from the first rupee. Excess TDS is refundable on filing ITR.',
  },
  {
    slug: 'nri-residency-status-determination',
    title: 'NRI Residency Status in India',
    subtitle: 'NR vs RNOR vs Resident 2026',
    excerpt: '182-day rule, modified 60-day rule, RNOR status for returning NRIs, deemed resident provisions (Section 6(1A)), and tax implications of each status.',
    category: 'compliance', topic: 'compliance',
    tags: ['Residency', 'RNOR', 'Section 6', '182 Days'],
    readTime: '8 min',
    featured: false,
    views: '86K+ source views',
    icon: '🌍',
    color: '#0891B2',
    keyNumbers: [
      { label: 'NR Threshold', value: '<182 days' },
      { label: 'Modified Rule', value: '60 days' },
      { label: 'RNOR Period', value: '2-3 years' },
      { label: 'Deemed Trigger', value: '₹15L income' },
    ],
    quickAnswer: 'NRI status requires staying in India less than 182 days (or 60 days with ₹15L+ Indian income). RNOR status gives returning NRIs 2-3 years of protection from global income taxation. Deemed resident provisions apply if not tax resident anywhere.',
  },
  {
    slug: 'nri-budget-2026-changes',
    title: 'Budget 2026 Impact on NRIs',
    subtitle: 'TCS Cut, Property TDS, Foreign Assets',
    excerpt: 'TCS on education/medical cut from 5% to 2%, TAN removed for NRI property TDS, Foreign Assets Disclosure Scheme with reduced penalties and immunity.',
    category: 'tax', topic: 'filing',
    tags: ['Budget 2026', 'TCS', 'TAN', 'Disclosure'],
    readTime: '8 min',
    featured: false,
    views: '74K+ source views',
    icon: '📜',
    color: '#E11D48',
    keyNumbers: [
      { label: 'TCS Education', value: '2% (was 5%)' },
      { label: 'TAN', value: 'Removed' },
      { label: 'NRI Stock Limit', value: '10%' },
      { label: 'Disclosure', value: '6-month window' },
    ],
    quickAnswer: 'Budget 2026 benefits for NRIs: TCS on education/medical remittance cut from 5% to 2%, TAN no longer needed for property TDS, NRI stock holding limit doubled to 10%, and a 6-month Foreign Assets Disclosure Scheme with immunity.',
  },
  {
    slug: 'nri-retirement-pension-planning',
    title: 'NRI Retirement Planning',
    subtitle: 'Pension, EPF, NPS & Return to India',
    excerpt: 'EPF withdrawal rules, PPF continuation, NPS for NRIs, pension taxation, SWP strategies, and planning for returning to India.',
    category: 'guide', topic: 'planning',
    tags: ['Retirement', 'Pension', 'EPF', 'NPS'],
    readTime: '12 min',
    featured: false,
    views: '3.86M+ source views',
    icon: '🏖️',
    color: '#4F46E5',
    keyNumbers: [
      { label: 'EPF', value: 'Withdrawable' },
      { label: 'PPF', value: 'Ext. till maturity' },
      { label: 'NPS', value: 'Available' },
      { label: 'SWP', value: 'Tax-efficient' },
    ],
    quickAnswer: 'NRIs can withdraw EPF after leaving India. PPF accounts continue till maturity but cannot accept new deposits. NPS is available to NRIs with tax benefits. Returning NRIs get RNOR status for 2-3 years, protecting foreign income.',
  },
  // ── NEW BATCH ──
  {
    slug: 'us-nri-tax-guide',
    title: 'US NRI Tax Guide',
    subtitle: 'India-US DTAA, FBAR, FATCA & Cross-Border Filing',
    excerpt: 'Complete guide for US-based NRIs: FBAR filing (USD 10K threshold), FATCA Form 8938, PFIC rules for Indian mutual funds, Social Security Totalisation, and India-US DTAA rates.',
    category: 'guide', topic: 'country',
    tags: ['US NRI', 'FBAR', 'FATCA', 'PFIC', 'India-US DTAA'],
    readTime: '18 min',
    featured: true,
    views: '2.75M+ source views',
    icon: '🇺🇸',
    color: '#1D4ED8',
    keyNumbers: [
      { label: 'FBAR Threshold', value: 'USD 10K' },
      { label: 'FATCA Threshold', value: 'USD 50K' },
      { label: 'DTAA Interest', value: '15%' },
      { label: 'FBAR Penalty', value: 'USD 12,909+' },
    ],
    quickAnswer: 'US NRIs must file FBAR (FinCEN 114) if aggregate Indian accounts exceed USD 10,000. Indian mutual funds are PFICs requiring Form 8621. India-US DTAA caps interest TDS at 15%. Private pension taxable only in the US.',
  },
  {
    slug: 'nri-esop-rsu-taxation',
    title: 'ESOP & RSU Taxation for NRIs',
    subtitle: 'Complete Cross-Border Guide 2026',
    excerpt: 'Two-stage taxation (perquisite + capital gains), cross-border apportionment, US Section 83(b) election, and practical computation examples.',
    category: 'tax', topic: 'income',
    tags: ['ESOP', 'RSU', 'Stock Options', 'Cross-Border'],
    readTime: '15 min',
    featured: false,
    views: '269K+ source views',
    icon: '📊',
    color: '#7C3AED',
    keyNumbers: [
      { label: 'Perquisite', value: 'FMV - Exercise' },
      { label: 'Listed LTCG', value: '12.5%' },
      { label: 'Unlisted LTCG', value: '12.5%' },
      { label: 'Apportionment', value: 'India days/Total' },
    ],
    quickAnswer: 'ESOP/RSU for NRIs is taxed in two stages: perquisite at slab rates (FMV minus exercise price) as salary, then capital gains on sale. Cross-border apportionment applies: only India-service portion is taxable in India.',
  },
  {
    slug: 'nri-tax-saving-strategies',
    title: 'Tax Saving Strategies for NRIs',
    subtitle: 'Deductions & Exemptions Guide 2026',
    excerpt: 'New vs old regime comparison, Section 80C/80D deductions, NRE interest exemption, GIFT City zero-tax route, Section 54/54EC, and Section 197 lower TDS.',
    category: 'tax', topic: 'planning',
    tags: ['Tax Saving', '80C', '80D', 'Deductions'],
    readTime: '14 min',
    featured: false,
    views: '3.48M+ source views',
    icon: '💡',
    color: '#059669',
    keyNumbers: [
      { label: '80C Limit', value: '₹1.5L' },
      { label: '80D Health', value: '₹25K-₹1L' },
      { label: 'Std Deduction', value: '₹75K' },
      { label: 'NRE Interest', value: 'Tax-Free' },
    ],
    quickAnswer: 'NRIs in the new regime get limited deductions: ₹75K standard deduction (salaried only), 30% on rental income. The biggest saver is NRE interest exemption under Section 10(4). Old regime offers 80C/80D but higher slab rates.',
  },
  {
    slug: 'nri-insurance-guide',
    title: 'NRI Insurance Guide',
    subtitle: 'Life, Health & Tax Benefits in India',
    excerpt: 'Term insurance for NRIs (cheaper in India), health insurance for parents, Section 80C/80D deductions, ULIP taxation, and claim process from abroad.',
    category: 'guide', topic: 'planning',
    tags: ['Insurance', 'Health', 'Term Plan', 'Section 80D'],
    readTime: '12 min',
    featured: false,
    views: '526K+ source views',
    icon: '🛡️',
    color: '#0891B2',
    keyNumbers: [
      { label: '80C Deduction', value: '₹1.5L' },
      { label: '80D Self', value: '₹25K' },
      { label: '80D Parents', value: '₹50K (60+)' },
      { label: 'ULIP Threshold', value: '₹2.5L' },
    ],
    quickAnswer: 'NRIs can buy term and health insurance in India. Section 80C allows deduction on life insurance premium, 80D on health insurance (₹25K self, ₹50K for senior parents). ULIP maturity is taxable if premium exceeds ₹2.5L/year.',
  },
  {
    slug: 'nri-buying-property-india',
    title: 'NRI Buying Property in India',
    subtitle: 'FEMA, Tax & Legal Guide 2026',
    excerpt: 'What NRIs can buy (no agricultural land), payment rules (NRE/NRO only), home loans, Power of Attorney, TDS obligations, RERA protection, and repatriation.',
    category: 'guide', topic: 'property',
    tags: ['Property Purchase', 'FEMA', 'Home Loan', 'POA'],
    readTime: '15 min',
    featured: false,
    views: '345K+ source views',
    icon: '🏗️',
    color: '#B45309',
    keyNumbers: [
      { label: 'Residential', value: 'Allowed' },
      { label: 'Agricultural', value: 'NOT Allowed' },
      { label: 'Payment', value: 'NRE/NRO Only' },
      { label: 'Max Properties', value: '2 (no RBI report)' },
    ],
    quickAnswer: 'NRIs can buy residential and commercial property in India but NOT agricultural land, farmhouse, or plantation. Payment must be from NRE/NRO/FCNR accounts — no cash or foreign currency. Budget 2026 removed TAN requirement for buyers.',
  },
  {
    slug: 'nri-ais-26as-reconciliation',
    title: 'AIS, 26AS & TIS Reconciliation',
    subtitle: 'Avoid Tax Notices — NRI Guide 2026',
    excerpt: 'How the tax department uses AIS to catch mismatches, handling NRE interest in AIS, TDS credit verification, property sale reporting, and the 5-step reconciliation process.',
    category: 'compliance', topic: 'compliance',
    tags: ['AIS', '26AS', 'TIS', 'Reconciliation'],
    readTime: '12 min',
    featured: false,
    views: '853K+ source views',
    icon: '🔍',
    color: '#DC2626',
    keyNumbers: [
      { label: 'SFT Property', value: '>₹30L' },
      { label: 'SFT FD', value: '>₹10L' },
      { label: 'Notice Risk', value: 'High if skip' },
      { label: 'Steps', value: '5-step process' },
    ],
    quickAnswer: 'The Income Tax Department uses AIS as its primary scrutiny tool. NRIs must reconcile AIS, 26AS, and TIS before filing ITR. Common issue: NRE interest appearing as taxable — file feedback to correct it. Mismatches trigger notices under 148/143.',
  },
  {
    slug: 'uae-nri-tax-guide',
    title: 'UAE/Dubai NRI Tax Guide',
    subtitle: 'India-UAE DTAA & Zero-Tax Trap',
    excerpt: 'Why "zero tax" in UAE doesn\'t mean zero Indian tax. DTAA rates (interest 12.5%, dividends 10%), TRC from Federal Tax Authority, and planning for UAE NRIs.',
    category: 'guide', topic: 'country',
    tags: ['UAE NRI', 'Dubai', 'Zero Tax', 'India-UAE DTAA'],
    readTime: '14 min',
    featured: false,
    views: '196K+ source views',
    icon: '🇦🇪',
    color: '#047857',
    keyNumbers: [
      { label: 'UAE Tax', value: '0%' },
      { label: 'DTAA Interest', value: '12.5%' },
      { label: 'DTAA Dividend', value: '10%' },
      { label: 'FTC Available', value: 'No (no UAE tax)' },
    ],
    quickAnswer: 'UAE has no personal income tax, but NRIs still owe full Indian tax on Indian income. No FTC is available since there is no UAE tax to credit. India-UAE DTAA reduces interest TDS to 12.5% (from 20%) and dividends to 10%.',
  },
  {
    slug: 'nri-income-tax-notice-response',
    title: 'NRI Income Tax Notice',
    subtitle: 'Types, Response & How to Handle',
    excerpt: 'Why NRIs get more notices, types (143/148/245/133), how to respond from abroad via e-proceedings, when to engage a CA, and common notice triggers.',
    category: 'compliance', topic: 'compliance',
    tags: ['Tax Notice', 'Scrutiny', 'Section 148', 'Appeal'],
    readTime: '14 min',
    featured: false,
    views: '1.23M+ source views',
    icon: '⚠️',
    color: '#B91C1C',
    keyNumbers: [
      { label: 'Response Time', value: '15-30 days' },
      { label: 'Penalty 270A', value: '50-200%' },
      { label: 'Rectification', value: 'Section 154' },
      { label: 'Appeal', value: 'CIT(A) → ITAT' },
    ],
    quickAnswer: 'NRIs receive more notices due to AIS mismatches, non-filing, and high TDS. Common types: 143(1) intimation, 143(2) scrutiny, 148 reassessment. All can be responded to online via e-proceedings — no India visit needed.',
  },
  // ── BATCH 3 ──
  {
    slug: 'nri-returning-to-india',
    title: 'NRI Returning to India',
    subtitle: 'RNOR Status, Tax Planning & Checklist',
    excerpt: 'RNOR qualification (9/10 years NRI), 2-3 year tax-free window on foreign income, FCNR maturity planning, account conversion, and comprehensive return checklist.',
    category: 'guide', topic: 'planning',
    tags: ['Returning NRI', 'RNOR', 'FCNR', 'Relocation'],
    readTime: '14 min',
    featured: false,
    views: '284K+ source views',
    icon: '🏡',
    color: '#6366F1',
    keyNumbers: [
      { label: 'RNOR Period', value: '2-3 years' },
      { label: 'Foreign Income', value: 'Not Taxed' },
      { label: 'FCNR', value: 'Plan Maturity' },
      { label: 'Account', value: 'Convert to RFC' },
    ],
    quickAnswer: 'Returning NRIs who were NRI in 9 of 10 preceding years qualify for RNOR status for 2-3 years. During RNOR, foreign income is NOT taxable in India — ideal window to mature FCNR deposits and liquidate overseas investments.',
  },
  {
    slug: 'nri-repatriation-guide',
    title: 'NRI Money Repatriation',
    subtitle: 'Form 15CA/CB, Limits & Process',
    excerpt: 'NRE unlimited vs NRO USD 1M cap, Form 15CA (4 parts), Form 15CB CA certificate, property sale repatriation, and common bank rejections.',
    category: 'compliance', topic: 'banking',
    tags: ['Repatriation', 'Form 15CA', 'Form 15CB', 'FEMA'],
    readTime: '12 min',
    featured: false,
    views: '242K+ source views',
    icon: '💸',
    color: '#0D9488',
    keyNumbers: [
      { label: 'NRE', value: 'Unlimited' },
      { label: 'NRO Cap', value: 'USD 1M/yr' },
      { label: 'Form 15CB', value: 'CA Required' },
      { label: 'Timeline', value: '4-6 weeks' },
    ],
    quickAnswer: 'NRE accounts: unlimited repatriation, no documentation. NRO accounts: capped at USD 1M per FY, requires Form 15CA + Form 15CB from a CA. Property sale proceeds need tax clearance before repatriation. Allow 4-6 weeks.',
  },
  {
    slug: 'nri-aadhaar-pan-oci-guide',
    title: 'Aadhaar, PAN & OCI for NRIs',
    subtitle: 'Complete Document Guide 2026',
    excerpt: 'PAN mandatory for all Indian income, Aadhaar enrollment on visit, OCI card rules, PAN-Aadhaar linking exemption, PAN 2.0, and digital KYC.',
    category: 'compliance', topic: 'compliance',
    tags: ['PAN Card', 'Aadhaar', 'OCI', 'Documents'],
    readTime: '10 min',
    featured: false,
    views: '441K+ source views',
    icon: '🪪',
    color: '#D97706',
    keyNumbers: [
      { label: 'PAN', value: 'Mandatory' },
      { label: 'Aadhaar', value: 'Voluntary' },
      { label: 'OCI Property', value: 'No Agri Land' },
      { label: 'Linking', value: 'NRI Exempt' },
    ],
    quickAnswer: 'PAN is mandatory for all NRIs with Indian income. Aadhaar is voluntary for NRIs but useful for e-verification. NRIs are exempt from PAN-Aadhaar linking if they don\'t have Aadhaar. OCI holders have same tax treatment as NRIs.',
  },
  {
    slug: 'nri-crypto-vda-tax',
    title: 'Crypto & VDA Tax for NRIs',
    subtitle: '30% Flat Rate Complete Guide',
    excerpt: 'Section 115BBH (30% flat), 1% TDS (Section 194S), NO loss set-off, mining/staking/DeFi taxation, and cross-border crypto reporting requirements.',
    category: 'tax', topic: 'income',
    tags: ['Crypto', 'VDA', 'Bitcoin', 'Section 115BBH'],
    readTime: '12 min',
    featured: false,
    views: '231K+ source views',
    icon: '₿',
    color: '#F59E0B',
    keyNumbers: [
      { label: 'Tax Rate', value: '30% Flat' },
      { label: 'TDS', value: '1% on Transfer' },
      { label: 'Loss Set-off', value: 'NOT Allowed' },
      { label: 'Deductions', value: 'Cost Only' },
    ],
    quickAnswer: 'Crypto/VDA gains in India are taxed at 30% flat (no slab benefit) under Section 115BBH. 1% TDS applies on transfers. Losses cannot be set off against any income or carried forward. Only cost of acquisition is deductible.',
  },
  {
    slug: 'nri-startup-business-india',
    title: 'NRI Starting Business in India',
    subtitle: 'Company, LLP & Compliance Guide',
    excerpt: 'Pvt Ltd vs LLP comparison, FDI automatic route, incorporation process, FEMA compliance, transfer pricing, GST, and Startup India benefits.',
    category: 'guide', topic: 'planning',
    tags: ['Startup', 'LLP', 'Company', 'FDI'],
    readTime: '14 min',
    featured: false,
    views: '259K+ source views',
    icon: '🚀',
    color: '#8B5CF6',
    keyNumbers: [
      { label: 'FDI Route', value: 'Automatic' },
      { label: 'Pvt Ltd', value: '2 Directors' },
      { label: 'LLP', value: '2 Partners' },
      { label: 'Startup 80-IAC', value: '3yr Tax Holiday' },
    ],
    quickAnswer: 'NRIs can start Pvt Ltd or LLP in India via FDI automatic route. Investment must come through NRE/NRO/FCNR. Director needs DIN + DSC. Startup India offers 3-year tax holiday under Section 80-IAC for eligible companies.',
  },
  {
    slug: 'nri-home-loan-india',
    title: 'NRI Home Loan in India',
    subtitle: 'Eligibility, Rates & Tax Benefits',
    excerpt: 'LTV 75-80%, interest rates 8.5-9.5%, documents needed, Section 24 interest deduction, Section 80C principal, and repayment from NRE/NRO.',
    category: 'banking', topic: 'property',
    tags: ['Home Loan', 'Mortgage', 'Section 24', 'EMI'],
    readTime: '12 min',
    featured: false,
    views: '222K+ source views',
    icon: '🏠',
    color: '#2563EB',
    keyNumbers: [
      { label: 'LTV Ratio', value: '75-80%' },
      { label: 'Interest', value: '8.5-9.5%' },
      { label: 'Sec 24 (Self)', value: '₹2L Cap' },
      { label: 'Sec 24 (Let-out)', value: 'No Cap' },
    ],
    quickAnswer: 'NRIs can get home loans from Indian banks with 75-80% LTV. Interest rates range 8.5-9.5%. Section 24 allows ₹2L interest deduction (self-occupied) or unlimited (let-out). EMI payable from NRE/NRO account.',
  },
  {
    slug: 'canada-nri-tax-guide',
    title: 'Canada NRI Tax Guide',
    subtitle: 'India-Canada DTAA, T1135 & RRSP',
    excerpt: 'India-Canada DTAA rates, T1135 foreign income verification (CAD 100K threshold), RRSP/TFSA treatment, and cross-border property sale planning.',
    category: 'guide', topic: 'country',
    tags: ['Canada NRI', 'T1135', 'RRSP', 'India-Canada DTAA'],
    readTime: '14 min',
    featured: false,
    views: '449K+ source views',
    icon: '🇨🇦',
    color: '#DC2626',
    keyNumbers: [
      { label: 'T1135 Threshold', value: 'CAD 100K' },
      { label: 'DTAA Interest', value: '15%' },
      { label: 'DTAA Dividend', value: '15-25%' },
      { label: 'CG Credit', value: 'FTC Available' },
    ],
    quickAnswer: 'Canadian NRIs must file T1135 if foreign assets exceed CAD 100,000. India-Canada DTAA caps interest at 15%. Property sale gains: pay Indian LTCG then claim FTC in Canada. RRSP withdrawals may be taxable in India if resident.',
  },
  {
    slug: 'nri-will-estate-succession',
    title: 'NRI Will & Estate Planning',
    subtitle: 'Succession Laws in India 2026',
    excerpt: 'Why NRIs need a separate Indian will, succession laws, probate process, nominee vs legal heir, cross-border estate planning, and inherited property tax.',
    category: 'guide', topic: 'compliance',
    tags: ['Will', 'Estate', 'Succession', 'Inheritance'],
    readTime: '14 min',
    featured: false,
    views: '24K+ source views',
    icon: '📜',
    color: '#78350F',
    keyNumbers: [
      { label: 'Inheritance Tax', value: 'None in India' },
      { label: 'Probate', value: '3 cities required' },
      { label: 'Nominee', value: '≠ Legal Heir' },
      { label: 'Will Registration', value: 'Recommended' },
    ],
    quickAnswer: 'India has no inheritance tax. NRIs need a separate Indian will for Indian assets. Nominee is custodian, NOT owner — legal heirs inherit. Probate is required in Kolkata, Mumbai, and Chennai. Inherited property CG uses previous owner\'s cost basis.',
  },
  // ── BATCH 4 ──
  {
    slug: 'nri-tax-mistakes-guide',
    title: '28 Costly NRI Tax Mistakes',
    subtitle: 'The Mega-Guide to Avoiding Penalties',
    excerpt: 'Every tax, TDS, property, banking, FEMA, and investment mistake NRIs make — with exact penalties and quick fixes for each.',
    category: 'guide', topic: 'compliance',
    tags: ['Mistakes', 'Penalties', 'Compliance', 'Checklist'],
    readTime: '20 min',
    featured: true,
    views: '1.35M+ source views',
    icon: '⚠️',
    color: '#DC2626',
    keyNumbers: [
      { label: 'Mistakes Covered', value: '28' },
      { label: 'Categories', value: '5' },
      { label: 'FEMA Penalty', value: 'Up to 3x' },
      { label: 'FBAR Penalty', value: 'USD 12,909+' },
    ],
    quickAnswer: 'The 28 most costly NRI mistakes: not filing ITR despite TDS (losing ₹2-15L refund), wrong ITR form, claiming Section 87A, not applying Section 197 (₹16L+ locked), keeping resident account (FEMA 3x penalty), US NRI FBAR non-filing (USD 12,909+ penalty).',
  },
  {
    slug: 'australia-nri-tax-guide',
    title: 'Australia NRI Tax Guide',
    subtitle: 'India-Australia DTAA, Superannuation & CGT',
    excerpt: 'India-Australia DTAA rates, ATO reporting, superannuation treatment, 50% CGT discount interaction with Indian LTCG, and Medicare levy implications.',
    category: 'guide', topic: 'country',
    tags: ['Australia NRI', 'DTAA', 'Superannuation', 'ATO'],
    readTime: '14 min',
    featured: false,
    views: '463K+ source views',
    icon: '🇦🇺',
    color: '#1D4ED8',
    keyNumbers: [
      { label: 'DTAA Interest', value: '15%' },
      { label: 'DTAA Dividend', value: '15%' },
      { label: 'CGT Discount', value: '50%' },
      { label: 'FTC', value: 'Available' },
    ],
    quickAnswer: 'Australia NRIs pay Indian LTCG on property sale and claim FTC in Australia. India-Australia DTAA caps interest at 15%. Superannuation lump-sum may be treated differently under the treaty. Australia\'s 50% CGT discount applies before FTC.',
  },
  {
    slug: 'nri-india-visit-checklist',
    title: 'NRI India Visit Checklist',
    subtitle: '25-Point Tax & Financial Checklist',
    excerpt: 'Everything to do before, during, and after your India visit — from day-count tracking to bank KYC, property documents, AIS checks, and repatriation planning.',
    category: 'compliance', topic: 'compliance',
    tags: ['India Visit', 'Checklist', 'KYC', 'Day Count'],
    readTime: '10 min',
    featured: false,
    views: '539K+ source views',
    icon: '✈️',
    color: '#0891B2',
    keyNumbers: [
      { label: 'Before', value: '8 items' },
      { label: 'During', value: '10 items' },
      { label: 'After', value: '7 items' },
      { label: 'Day Limit', value: '182 days' },
    ],
    quickAnswer: 'Before: count days, submit TRC to banks, check AIS. During: update KYC in person, meet CA, sign property docs. Before returning: verify day count, initiate repatriation, check IT portal for notices.',
  },
  {
    slug: 'nri-financial-planning-by-age',
    title: 'NRI Financial Planning by Age',
    subtitle: '25-35, 35-50, 50+ Complete Roadmap',
    excerpt: 'Age-appropriate SIP amounts, asset allocation, insurance coverage, GIFT City strategy, RNOR transition planning, and SWP for retirement income.',
    category: 'guide', topic: 'planning',
    tags: ['Financial Planning', 'SIP', 'Asset Allocation', 'Retirement'],
    readTime: '16 min',
    featured: true,
    views: '810K+ source views',
    icon: '📐',
    color: '#7C3AED',
    keyNumbers: [
      { label: '25-35 Equity', value: '70-80%' },
      { label: '35-50 Equity', value: '50-60%' },
      { label: '50+ Equity', value: '30-40%' },
      { label: 'SIP Goal', value: '10-20% income' },
    ],
    quickAnswer: 'Age 25-35: Start SIPs ₹10-50K/month, 70-80% equity, term insurance from India. Age 35-50: Diversify, property planning, children\'s education fund. Age 50+: Shift to SWP, FCNR laddering, will preparation, RNOR planning.',
  },
  {
    slug: 'nri-tax-case-studies',
    title: '7 Real NRI Tax Case Studies',
    subtitle: 'How We Saved Our Clients Lakhs',
    excerpt: 'Anonymized real cases: ₹16L saved via Section 197, ₹2.7L refund recovered, 60% ESOP reduction, FEMA compounding, RNOR planning savings.',
    category: 'guide', topic: 'planning',
    tags: ['Case Studies', 'Tax Savings', 'Client Stories', 'Results'],
    readTime: '15 min',
    featured: true,
    views: '132K+ source views',
    icon: '📋',
    color: '#059669',
    keyNumbers: [
      { label: 'Cases', value: '7' },
      { label: 'Total Saved', value: '₹1.4Cr+' },
      { label: 'Countries', value: '6' },
      { label: 'Success Rate', value: '100%' },
    ],
    quickAnswer: 'Real results: US NRI saved ₹16L on property sale (Section 197), UAE NRI recovered ₹2.7L TDS refund, UK NRI reduced ESOP tax by 60%, Singapore NRI FEMA penalty reduced from ₹15L to ₹2L, returning NRI saved ₹18L through RNOR.',
  },
  {
    slug: 'nri-sip-investment-strategy',
    title: 'NRI SIP Investment Strategy',
    subtitle: 'Step-Up, Trigger & Tax-Efficient Playbook',
    excerpt: 'SIP from NRE vs NRO, step-up SIP, trigger SIP, FIFO taxation, best MF categories, GIFT City alternative, and 10-year return simulations.',
    category: 'investment', topic: 'planning',
    tags: ['SIP', 'Step-Up SIP', 'Mutual Funds', 'Tax-Efficient'],
    readTime: '14 min',
    featured: false,
    views: '123K+ source views',
    icon: '📊',
    color: '#2563EB',
    keyNumbers: [
      { label: 'NRE SIP', value: 'Repatriable' },
      { label: 'Step-Up', value: '+10%/year' },
      { label: '10yr ₹25K SIP', value: '~₹58L' },
      { label: 'GIFT City', value: '0% Tax' },
    ],
    quickAnswer: 'NRI SIPs via NRE are fully repatriable. Step-up SIP (increase 10%/year) maximizes compounding. Each SIP unit is taxed separately (FIFO). ₹25K/month for 10 years at 12% = ~₹58L. GIFT City SIP offers zero-tax alternative.',
  },
  {
    slug: 'nri-money-transfer-india',
    title: 'Sending Money to/from India',
    subtitle: 'Cheapest, Fastest & Compliant Methods',
    excerpt: 'SWIFT vs Wise vs UPI comparison, NRE vs NRO deposits, LRS outward limits, TCS rules (Budget 2026: 2% for education), and Form 15CA/15CB for outward.',
    category: 'banking', topic: 'banking',
    tags: ['Wire Transfer', 'Remittance', 'UPI', 'LRS', 'TCS'],
    readTime: '12 min',
    featured: false,
    views: '151K+ source views',
    icon: '💱',
    color: '#0D9488',
    keyNumbers: [
      { label: 'Wise Fee', value: '0.5-1%' },
      { label: 'SWIFT', value: '2-3 days' },
      { label: 'LRS Limit', value: 'USD 250K/yr' },
      { label: 'TCS Education', value: '2%' },
    ],
    quickAnswer: 'Cheapest: Wise (0.5-1% fee, mid-market rate). Fastest: UPI for NRIs (instant). SWIFT: 2-3 days, higher fees. Inward to NRE = tax-free interest. Outward from India: LRS USD 250K/year with 5% TCS above ₹7L (education/medical: 2%).',
  },
  {
    slug: 'gulf-gcc-nri-tax-guide',
    title: 'Gulf/GCC NRI Tax Guide',
    subtitle: 'Saudi, Qatar, Oman, Bahrain, Kuwait',
    excerpt: 'DTAA rates per GCC country, TRC process, zero-tax trap, end-of-service gratuity, Kuwait special case (no DTAA!), and return-to-India RNOR planning.',
    category: 'guide', topic: 'country',
    tags: ['Gulf NRI', 'GCC', 'Saudi', 'Qatar', 'Kuwait'],
    readTime: '14 min',
    featured: false,
    views: '46K+ source views',
    icon: '🏜️',
    color: '#B45309',
    keyNumbers: [
      { label: 'Saudi DTAA', value: 'Yes' },
      { label: 'Kuwait DTAA', value: 'NO!' },
      { label: 'EOSB Tax', value: 'Not in India' },
      { label: 'Zero-Tax Trap', value: 'Applies' },
    ],
    quickAnswer: 'All GCC countries have zero/low personal tax — the zero-tax trap applies (no FTC). Kuwait has NO DTAA with India (Section 91 unilateral relief only). End-of-service gratuity (EOSB) is generally not taxable in India if received abroad.',
  },
  // ── BATCH 5 ──
  {
    slug: 'nri-gift-tax-rules',
    title: 'NRI Gift Tax Rules',
    subtitle: 'Section 56(2)(x), Gifted Property & Implications',
    excerpt: 'No gift tax since 1998 but Section 56(2)(x) taxes gifts >₹50K from non-relatives. Gifted property CG uses donor\'s cost. FEMA rules for NRI gifts.',
    category: 'tax', topic: 'income',
    tags: ['Gift Tax', 'Section 56', 'Gift Deed', 'Clubbing'],
    readTime: '12 min', featured: false, views: '177K+ source views', icon: '🎁', color: '#E11D48',
    keyNumbers: [{ label: 'Exempt Limit', value: '₹50K' }, { label: 'Relative', value: 'Tax-Free' }, { label: 'CG Cost', value: "Donor's Cost" }, { label: 'Clubbing', value: 'Sec 64' }],
    quickAnswer: 'Gifts from relatives (spouse, siblings, parents, children) are fully tax-free regardless of amount. Gifts >₹50K from non-relatives are taxable under Section 56(2)(x). Gifted property CG uses donor\'s cost basis and holding period.',
  },
  {
    slug: 'nri-fixed-deposit-strategies',
    title: 'NRI Fixed Deposit Guide',
    subtitle: 'NRE vs NRO vs FCNR FD Rates & Strategies',
    excerpt: 'NRE FD tax-free interest, NRO FD 30% TDS (DTAA reduces to 10-15%), FCNR zero forex risk. FD laddering, best rates, and RNOR maturity planning.',
    category: 'banking', topic: 'banking',
    tags: ['Fixed Deposit', 'FD Rates', 'NRE FD', 'FCNR'],
    readTime: '12 min', featured: false, views: '339K+ source views', icon: '🏦', color: '#1D4ED8',
    keyNumbers: [{ label: 'NRE FD', value: 'Tax-Free' }, { label: 'NRO TDS', value: '30%' }, { label: 'FCNR', value: 'No FX Risk' }, { label: 'Best Rate', value: '~7.5%' }],
    quickAnswer: 'NRE FD interest is 100% tax-free under Section 10(4). NRO FD faces 30% TDS (reducible to 10-15% with DTAA). FCNR deposits held in USD/GBP eliminate currency risk with tax-free interest. Ladder maturities for liquidity.',
  },
  {
    slug: 'nri-freelancer-consultant-tax',
    title: 'NRI Freelancer & Consultant Tax',
    subtitle: 'FTS, TDS & ITR-3 Guide',
    excerpt: 'When freelance income is taxable for NRIs, Section 115A FTS 10%, Section 44ADA presumptive taxation, GST for NRI consultants, and DTAA FTS rates.',
    category: 'tax', topic: 'income',
    tags: ['Freelancer', 'Consultant', 'FTS', 'Section 44ADA'],
    readTime: '12 min', featured: false, views: '306K+ source views', icon: '💻', color: '#7C3AED',
    keyNumbers: [{ label: 'FTS TDS', value: '10%' }, { label: 'Presumptive', value: '50% of gross' }, { label: 'GST Threshold', value: '₹20L' }, { label: 'ITR Form', value: 'ITR-3' }],
    quickAnswer: 'NRI freelancer/consultant income is taxable in India if services are rendered IN India. TDS at 10% under Section 195. Section 44ADA allows presumptive taxation at 50% of gross receipts. GST applies above ₹20L threshold.',
  },
  {
    slug: 'nri-parents-care-financial-guide',
    title: 'NRI Parents Care Guide',
    subtitle: 'Health Insurance, Tax & Planning from Abroad',
    excerpt: 'Section 80D for parents (₹25K-₹50K), senior citizen ITR, Form 15H, sending money to parents (gift = tax-free), POA for property management.',
    category: 'guide', topic: 'income',
    tags: ['Parents', 'Health Insurance', 'Senior Citizen', 'Section 80D'],
    readTime: '12 min', featured: false, views: '185K+ source views', icon: '👨‍👩‍👦', color: '#059669',
    keyNumbers: [{ label: '80D (Under 60)', value: '₹25K' }, { label: '80D (60+)', value: '₹50K' }, { label: 'Gift to Parents', value: 'Tax-Free' }, { label: 'Form 15H', value: 'No TDS' }],
    quickAnswer: 'NRIs can claim Section 80D for parents\' health insurance (₹25K under 60, ₹50K for 60+). Money sent to parents is a gift from relative — fully tax-free. Parents can submit Form 15H to avoid TDS on FD interest.',
  },
  {
    slug: 'nri-vs-resident-tax-comparison',
    title: 'NRI vs Resident Tax Comparison',
    subtitle: 'Complete Side-by-Side Reference 2026',
    excerpt: 'Every difference: income scope, Section 87A, TDS rates, bank accounts, FEMA, DTAA, Schedule FA, NRE interest — massive comparison tables.',
    category: 'tax', topic: 'filing',
    tags: ['NRI vs Resident', 'Comparison', 'Section 87A', 'TDS Rates'],
    readTime: '10 min', featured: false, views: '75K+ source views', icon: '⚖️', color: '#6366F1',
    keyNumbers: [{ label: 'NRI 87A', value: 'NOT Available' }, { label: 'NRI NRO TDS', value: '30%' }, { label: 'Resident TDS', value: '10%' }, { label: 'NRE Interest', value: 'NRI=Free' }],
    quickAnswer: 'Key differences: NRIs pay tax only on Indian income (residents on worldwide). Section 87A rebate is NOT for NRIs. NRI TDS is 3x higher (NRO 30% vs resident 10%). NRE interest is tax-free for NRIs but taxable for residents.',
  },
  {
    slug: 'nri-schedule-fa-foreign-assets',
    title: 'Schedule FA — Foreign Assets',
    subtitle: 'Disclosure Rules for Returning NRIs',
    excerpt: 'Mandatory for Residents/RNOR. What to disclose (bank, securities, property, trusts). Black Money Act penalty ₹10L. Budget 2026 disclosure scheme.',
    category: 'compliance', topic: 'compliance',
    tags: ['Schedule FA', 'Foreign Assets', 'Black Money Act', 'RNOR'],
    readTime: '10 min', featured: false, views: '59K+ source views', icon: '📑', color: '#DC2626',
    keyNumbers: [{ label: 'Who Files', value: 'Resident/RNOR' }, { label: 'Penalty', value: '₹10L' }, { label: 'BMA Tax', value: '30%+90%' }, { label: 'Disclosure', value: '6-month window' }],
    quickAnswer: 'Residents and RNOR must disclose ALL foreign assets in Schedule FA (FA1-FA7). Non-disclosure penalty: ₹10L under Black Money Act. Undisclosed foreign income: 30% tax + 90% penalty. Budget 2026 offers a 6-month amnesty window.',
  },
  {
    slug: 'nri-indian-pension-tax',
    title: 'NRI Pension from India',
    subtitle: 'EPS, Government & Private Pension Tax',
    excerpt: 'Indian pension IS taxable for NRIs. DTAA treatment varies by country (US: private pension exempt, UK: credit method). EPS, NPS withdrawal rules.',
    category: 'tax', topic: 'income',
    tags: ['Pension', 'EPS', 'NPS', 'DTAA Pension'],
    readTime: '12 min', featured: false, views: '53K+ source views', icon: '🧓', color: '#B45309',
    keyNumbers: [{ label: 'EPS Pension', value: 'Taxable in India' }, { label: 'US DTAA', value: 'Exempt in India' }, { label: 'NPS Lump Sum', value: '60% tax-free' }, { label: 'Commutation', value: '1/3 exempt (Govt)' }],
    quickAnswer: 'Indian pension accruing in India is taxable for NRIs under Section 5(2). DTAA treatment varies: under India-US treaty, private pension is taxable only in the US. EPS pension is credited to NRO. NPS: 60% lump sum, 40% annuity.',
  },
  {
    slug: 'nri-market-crash-guide',
    title: 'NRI Market Crash Survival Guide',
    subtitle: 'What to Do When Markets Fall',
    excerpt: 'Why NRIs face double hit (market + rupee), SIP advantage during crashes, tax-loss harvesting, rebalancing strategy, historical recovery data.',
    category: 'investment', topic: 'planning',
    tags: ['Market Crash', 'Volatility', 'SIP', 'Tax-Loss Harvesting'],
    readTime: '12 min', featured: false, views: '50K+ source views', icon: '📉', color: '#B91C1C',
    keyNumbers: [{ label: '2020 Recovery', value: '12 months' }, { label: '2008 Recovery', value: '18 months' }, { label: 'SIP Advantage', value: 'More units' }, { label: 'Tax Harvest', value: 'Offset gains' }],
    quickAnswer: 'NRIs face double impact during crashes (market fall + rupee depreciation). Continue SIPs — you buy more units at lower prices. Historical data: markets recover within 12-18 months. Tax-loss harvest to offset future capital gains.',
  },
  // ── BATCH 6 ──
  {
    slug: 'nri-tax-calendar-deadlines-2026',
    title: 'NRI Tax Calendar 2026',
    subtitle: 'Every Deadline & Due Date',
    excerpt: 'Month-by-month timeline: advance tax installments, ITR due dates, TDS returns, Section 54EC deadlines, penalty rates for missing each date.',
    category: 'compliance', topic: 'filing', tags: ['Calendar', 'Deadlines', 'Due Dates', 'Advance Tax'],
    readTime: '8 min', featured: false, views: '433K+ source views', icon: '📅', color: '#6366F1',
    keyNumbers: [{ label: 'ITR Due', value: '31 Jul 2026' }, { label: '234A Interest', value: '1%/month' }, { label: 'Late Fee', value: '₹5,000' }, { label: 'Advance Tax', value: '4 installments' }],
    quickAnswer: 'Key dates: Jun 15 (advance tax 15%), Sep 15 (45%), Dec 15 (75%), Mar 15 (100%), Jul 31 2026 (ITR due). Late filing: ₹5,000 penalty + 1% interest/month. Missing advance tax: 234B + 234C interest.',
  },
  {
    slug: 'nri-tds-rate-card-2026',
    title: 'NRI TDS Rate Card 2026',
    subtitle: 'Quick-Reference Table — Print & Save',
    excerpt: 'One-page reference: every TDS rate for NRIs, DTAA rates by country, surcharge table, effective rates, NRI vs Resident comparison — all in tables.',
    category: 'tax', topic: 'filing', tags: ['TDS Card', 'Rate Table', 'Quick Reference', 'DTAA Rates'],
    readTime: '5 min', featured: false, views: '262K+ source views', icon: '📊', color: '#DC2626',
    keyNumbers: [{ label: 'NRO Interest', value: '30%' }, { label: 'Property', value: '12.5-20%' }, { label: 'Dividends', value: '20%' }, { label: 'DTAA Range', value: '10-15%' }],
    quickAnswer: 'NRI TDS at a glance: NRO interest 30%, property LTCG 12.5%, STCG 30%, dividends 20%, rent 30%, professional fees 10%. DTAA reduces: US/UK/Canada 15%, UAE 12.5%, Germany 10%. Always add 4% cess.',
  },
  {
    slug: 'nri-power-of-attorney-guide',
    title: 'NRI Power of Attorney Guide',
    subtitle: 'GPA vs SPA, Registration & Property',
    excerpt: 'GPA vs SPA, Supreme Court Suraj Lamp ruling, property transaction limits, notarization abroad, apostille process, stamp duty, revocation, risks.',
    category: 'compliance', topic: 'compliance', tags: ['POA', 'GPA', 'SPA', 'Property Transactions'],
    readTime: '12 min', featured: false, views: '218K+ source views', icon: '📝', color: '#7C3AED',
    keyNumbers: [{ label: 'GPA', value: 'Cannot Transfer Title' }, { label: 'SPA', value: 'Specific Acts Only' }, { label: 'Registration', value: 'Mandatory for Property' }, { label: 'Apostille', value: 'Required Abroad' }],
    quickAnswer: 'GPA cannot transfer property title (Supreme Court, Suraj Lamp 2011). Use SPA for specific transactions. POA for property must be registered. From abroad: notarize at Indian embassy/consulate + apostille.',
  },
  {
    slug: 'nri-investment-comparison-nre-fd-gift-city-mf',
    title: 'Where Should NRIs Park Money?',
    subtitle: 'NRE FD vs GIFT City vs Debt MF vs NRO FD',
    excerpt: 'Head-to-head: 8 investment options compared on returns, tax, liquidity, risk, repatriation. Decision matrix by goal: safety, growth, tax-efficiency.',
    category: 'investment', topic: 'planning', tags: ['Comparison', 'NRE FD', 'GIFT City', 'Debt MF'],
    readTime: '14 min', featured: true, views: '134K+ source views', icon: '🎯', color: '#059669',
    keyNumbers: [{ label: 'NRE FD', value: '7.5% Tax-Free' }, { label: 'GIFT City', value: '0% Tax' }, { label: 'Debt MF', value: '12.5% LTCG' }, { label: 'Equity MF', value: '12.5% >₹1.25L' }],
    quickAnswer: 'Best tax-free: NRE FD (7.5%) or GIFT City (0% on 10%+ returns). Best growth: Equity MF via NRE (12.5% LTCG) or GIFT City equity (0%). Best safety: FCNR FD (no FX risk). Best liquidity: Debt MF (instant redemption).',
  },
  {
    slug: 'nri-section-54-exemption-guide',
    title: 'Section 54, 54EC, 54F Guide',
    subtitle: 'Complete Capital Gains Exemption Deep-Dive',
    excerpt: 'All three exemptions in depth: Section 54 (₹10Cr cap, 2yr/3yr timeline, CGAS), 54EC (₹50L bonds, 6-month deadline), 54F (proportional formula).',
    category: 'tax', topic: 'property', tags: ['Section 54', 'Section 54EC', 'Section 54F', 'CGAS'],
    readTime: '15 min', featured: false, views: 'High demand', icon: '🏠', color: '#2A6B4A',
    keyNumbers: [{ label: 'Sec 54 Cap', value: '₹10Cr' }, { label: '54EC Limit', value: '₹50L' }, { label: '54EC Deadline', value: '6 months' }, { label: '54F Formula', value: 'Proportional' }],
    quickAnswer: 'Section 54: reinvest LTCG in new house within 2 years (cap ₹10Cr). Section 54EC: invest up to ₹50L in NHAI/REC bonds within 6 months (5-year lock-in). Section 54F: for non-residential asset sale, invest net consideration proportionally.',
  },
  {
    slug: 'nri-joint-property-ownership',
    title: 'NRI Joint Property Ownership',
    subtitle: 'Tax, FEMA & Legal Guide',
    excerpt: 'NRI + Resident spouse, ownership ratio, proportional TDS and CG, Section 54 per co-owner, FEMA payment rules, adding/removing names, succession.',
    category: 'tax', topic: 'property', tags: ['Joint Property', 'Co-Owner', 'Spouse', 'FEMA'],
    readTime: '12 min', featured: false, views: 'High demand', icon: '🏘️', color: '#B07D3A',
    keyNumbers: [{ label: 'TDS', value: 'Per Share' }, { label: 'CG', value: 'Separate' }, { label: 'Sec 54', value: 'Each Owner' }, { label: 'FEMA', value: 'NRI pays from NRE/NRO' }],
    quickAnswer: 'Joint property: each co-owner computes capital gains separately based on ownership %. TDS is proportional. Each co-owner can claim Section 54 independently. NRI co-owner must pay their share from NRE/NRO account.',
  },
  {
    slug: 'nri-bank-account-opening-online',
    title: 'NRI Bank Account Opening Online',
    subtitle: 'Step-by-Step NRE, NRO & FCNR Guide',
    excerpt: 'Video KYC process, bank-by-bank comparison (SBI, HDFC, ICICI, Axis, Kotak), documents needed, converting resident to NRO, timeline 3-10 days.',
    category: 'banking', topic: 'banking', tags: ['Account Opening', 'Video KYC', 'Digital', 'Banks'],
    readTime: '10 min', featured: false, views: '74K+ source views', icon: '📱', color: '#0D9488',
    keyNumbers: [{ label: 'Timeline', value: '3-10 days' }, { label: 'Video KYC', value: 'Most Banks' }, { label: 'Min Balance', value: 'Varies' }, { label: 'Convert', value: 'Mandatory' }],
    quickAnswer: 'Most Indian banks now offer online NRI account opening via video KYC — SBI, HDFC, ICICI, Axis, Kotak. Documents: passport, visa, overseas address proof, PAN. Converting resident account to NRO is mandatory when becoming NRI.',
  },
  {
    slug: 'nri-mutual-fund-kyc-process',
    title: 'NRI Mutual Fund KYC Process',
    subtitle: 'Step-by-Step Onboarding Guide',
    excerpt: 'The #1 blocker for NRI MF investment — solved. CKYC, IPV options abroad, FATCA certification, US/Canada restrictions, and switching from Resident folio.',
    category: 'investment', topic: 'planning', tags: ['KYC', 'Mutual Fund', 'FATCA', 'Onboarding'],
    readTime: '10 min', featured: false, views: '22K+ source views', icon: '✅', color: '#2563EB',
    keyNumbers: [{ label: 'Steps', value: '7' }, { label: 'Timeline', value: '5-15 days' }, { label: 'IPV', value: 'Required' }, { label: 'US NRI', value: 'Limited AMCs' }],
    quickAnswer: 'NRI MF KYC: PAN verification → KRA registration → FATCA self-certification → In-Person Verification (embassy/video KYC/India visit) → AMC folio → bank mandate → first investment. US NRIs: only SBI MF, UTI, PPFAS accept.',
  },
  {
    slug: 'digital-nomad-tax-india',
    title: 'Digital Nomad Working from India',
    subtitle: 'Tax Traps, Residency & Compliance',
    excerpt: 'When remote work from India triggers tax liability, 182-day residency trap, employer PE risk, DTAA safe harbour, visa considerations, and how to stay compliant.',
    category: 'tax', topic: 'income', tags: ['Digital Nomad', 'Remote Work', 'PE Risk', 'Residency'],
    readTime: '12 min', featured: false, views: '19K+ source views', icon: '💻', color: '#8B5CF6',
    keyNumbers: [{ label: 'Trigger', value: 'Services in India' }, { label: 'Day Limit', value: '182 days' }, { label: 'DTAA Safe', value: '183 days' }, { label: 'Visa', value: 'Tourist ≠ Work' }],
    quickAnswer: 'Working remotely FROM India triggers Indian tax if services are "rendered in India" — even if paid by foreign employer. 182+ days = Resident (worldwide income taxable). Tourist visa technically doesn\'t permit work. Stay under 182 days.',
  },
  {
    slug: 'nri-rent-vs-buy-property-india',
    title: 'Should NRIs Rent or Buy in India?',
    subtitle: 'Decision Framework 2026',
    excerpt: 'Price-to-rent ratios, total cost of ownership vs rent, SIP vs EMI projection, NRI-specific hassles (POA, tenant, FEMA), and practical decision checklist.',
    category: 'guide', topic: 'property', tags: ['Rent vs Buy', 'Property', 'Decision', 'Investment'],
    readTime: '12 min', featured: false, views: '33K+ source views', icon: '🏠', color: '#B45309',
    keyNumbers: [{ label: 'Mumbai P/R', value: '30x' }, { label: 'Bangalore P/R', value: '25x' }, { label: 'SIP vs EMI', value: 'SIP often wins' }, { label: 'Liquidity', value: 'Property = Low' }],
    quickAnswer: 'If price-to-rent ratio >25x, renting is financially better. ₹50K/month SIP at 12% for 10 years = ₹1.16Cr vs same EMI on ₹60L property = ₹80L value. Buy only if returning within 5 years or strong emotional reason.',
  },
  {
    slug: 'india-vs-us-stock-market-nri',
    title: 'India vs US Stock Market for NRIs',
    subtitle: 'Returns, Tax & Allocation Strategy',
    excerpt: 'Nifty 50 vs S&P 500 in USD terms, rupee depreciation factor, tax comparison, GIFT City zero-tax route, and optimal dual-market allocation models.',
    category: 'investment', topic: 'planning', tags: ['India vs US', 'Nifty', 'S&P 500', 'Allocation'],
    readTime: '14 min', featured: false, views: '80K+ source views', icon: '📈', color: '#1D4ED8',
    keyNumbers: [{ label: 'Nifty 10yr', value: '~12% INR' }, { label: 'S&P 10yr', value: '~11% USD' }, { label: 'INR Depreciation', value: '3-4%/yr' }, { label: 'GIFT City', value: '0% on India' }],
    quickAnswer: 'Nifty 50 returns ~12% in INR but ~8% in USD after rupee depreciation. S&P 500 returns ~11% in USD. For US NRIs: 60% US + 40% India via GIFT City (0% tax) is optimal. Low correlation = great diversification.',
  },
  {
    slug: 'nri-itr-document-checklist',
    title: 'NRI ITR Document Checklist',
    subtitle: 'Every Paper You Need for AY 2026-27',
    excerpt: 'Categorized checklist: identity, income docs (26AS, AIS, Form 16A), deduction proofs, property sale papers, DTAA docs — with where to get each one.',
    category: 'compliance', topic: 'filing', tags: ['Document Checklist', 'ITR', 'Form 26AS', 'AIS'],
    readTime: '8 min', featured: false, views: '29K+ source views', icon: '📋', color: '#059669',
    keyNumbers: [{ label: 'Categories', value: '5' }, { label: 'Documents', value: '25+' }, { label: 'Start', value: '6 weeks early' }, { label: 'Most Missed', value: 'Form 67' }],
    quickAnswer: 'Essential NRI ITR documents: PAN, passport, Form 26AS + AIS (e-filing portal), Form 16A (from banks/tenants), NRO statements, property deeds, brokerage statements, TRC + Form 10F (for DTAA). Start collecting 6 weeks before July 31.',
  },
  // ── BATCH 7 (Final) ──
  { slug: 'nri-tax-myths-busted', title: '15 NRI Tax Myths Busted', subtitle: 'What You Think You Know Is Wrong', excerpt: '15 dangerous myths with real cost of believing each: Section 87A, TDS as final tax, NRE in ITR, ITR-1, resident account, property TDS 1%, and more.', category: 'guide', topic: 'compliance', tags: ['Myths', 'Misconceptions', 'Common Errors'], readTime: '12 min', featured: true, views: '13K+', icon: '💥', color: '#DC2626', keyNumbers: [{ label: 'Myths', value: '15' }, { label: 'Cost', value: '₹2-15L each' }, { label: 'Most Dangerous', value: '87A Rebate' }, { label: 'FEMA Risk', value: '3x Penalty' }], quickAnswer: 'Top myths: "87A rebate applies to NRIs" (wrong — ₹25K loss), "TDS is final tax" (wrong — lose ₹2-15L refund), "NRE interest goes in ITR" (wrong — it\'s exempt), "I can use ITR-1" (wrong — defective return).' },
  { slug: 'nri-tax-glossary', title: 'NRI Tax Glossary A-Z', subtitle: '75 Essential Terms Explained', excerpt: 'Every abbreviation and term NRIs encounter: AIS, CGAS, CII, DTAA, FBAR, FEMA, GIFT City, LTCG, PIS, RNOR, TRC — grouped by category with NRI-specific definitions.', category: 'compliance', topic: 'compliance', tags: ['Glossary', 'Terms', 'Dictionary', 'Reference'], readTime: '10 min', featured: false, views: '19K+', icon: '📖', color: '#6366F1', keyNumbers: [{ label: 'Terms', value: '75' }, { label: 'Categories', value: '6' }, { label: 'Format', value: 'A-Z' }, { label: 'Bookmark', value: 'This Page' }], quickAnswer: 'Quick reference: AIS = Annual Information Statement, CGAS = Capital Gains Account Scheme, CII = Cost Inflation Index, DTAA = Double Tax Avoidance Agreement, FBAR = Foreign Bank Account Report, RNOR = Resident Not Ordinarily Resident.' },
  { slug: 'nri-quick-tax-tips-50', title: '50 Quick NRI Tax Tips', subtitle: 'Scannable Tips That Save Lakhs', excerpt: '50 actionable 1-3 sentence tips across filing, TDS, property, banking, investment, and compliance — the ultimate scannable reference.', category: 'guide', topic: 'filing', tags: ['Tips', 'Quick Reference', 'Actionable', 'Save Tax'], readTime: '15 min', featured: true, views: '104K+', icon: '⚡', color: '#F59E0B', keyNumbers: [{ label: 'Tips', value: '50' }, { label: 'Categories', value: '6' }, { label: 'Format', value: 'Scannable' }, { label: 'Top 5', value: 'Quick Wins' }], quickAnswer: 'Top 5 quick wins: (1) File ITR even if income <₹4L to claim TDS refund, (2) Submit TRC to banks in April for DTAA rates, (3) Apply Section 197 before property sale, (4) NRE FD = tax-free interest, (5) Compare both regimes before filing.' },
  { slug: 'nri-senior-citizen-tax-benefits', title: 'NRI Senior Citizen Tax Benefits', subtitle: 'Tax Guide for 60+ NRIs', excerpt: 'Higher exemption in old regime, 80TTB limitation, Form 15H (residents only), SCSS on return, 80D ₹50K for seniors, RNOR benefits for returning seniors.', category: 'tax', topic: 'income', tags: ['Senior Citizen', '60+', 'Pension', 'Form 15H'], readTime: '10 min', featured: false, views: '142K+', icon: '🧓', color: '#B45309', keyNumbers: [{ label: 'Old Regime', value: '₹3L/₹5L exempt' }, { label: '80TTB', value: 'NOT for NRI' }, { label: '80D (60+)', value: '₹50K' }, { label: 'Form 15H', value: 'Residents Only' }], quickAnswer: 'NRI seniors get higher exemption (₹3L/₹5L) in old regime only. Section 80TTB (₹50K interest deduction) is NOT for NRIs. Form 15H is for resident seniors only. Returning seniors get RNOR + senior benefits combined.' },
  { slug: 'nri-student-abroad-tcs-education', title: 'NRI Children Studying Abroad', subtitle: 'TCS on Education & Loan Tax Guide', excerpt: 'Budget 2026: TCS cut to 2% on education remittance. Section 80E loan deduction. NRE route avoids TCS. Scholarship exemption. Practical examples.', category: 'tax', topic: 'income', tags: ['Education', 'TCS', 'Student', 'Section 80E'], readTime: '10 min', featured: false, views: '182K+', icon: '🎓', color: '#2563EB', keyNumbers: [{ label: 'TCS Education', value: '2% (was 5%)' }, { label: 'Threshold', value: '₹7L' }, { label: 'Loan TCS', value: '0.5%' }, { label: '80E Deduction', value: 'No Limit' }], quickAnswer: 'Budget 2026 cut TCS on education remittance from 5% to 2%. Threshold: ₹7L aggregate LRS per FY. Education loan funded = only 0.5% TCS. Section 80E: unlimited interest deduction for 8 years (old regime). NRE route avoids TCS entirely.' },
  { slug: 'nri-advance-tax-guide', title: 'NRI Advance Tax Guide', subtitle: 'When, How Much & How to Pay', excerpt: 'When advance tax applies (>₹10K after TDS), 4-installment computation, online payment via Challan 280, Section 234B/234C interest, practical examples.', category: 'tax', topic: 'filing', tags: ['Advance Tax', 'Section 234B', 'Section 234C', 'Challan 280'], readTime: '10 min', featured: false, views: '81K+', icon: '📊', color: '#0891B2', keyNumbers: [{ label: 'Trigger', value: '>₹10K' }, { label: 'Jun 15', value: '15%' }, { label: 'Sep 15', value: '45%' }, { label: 'Interest', value: '1%/month' }], quickAnswer: 'Pay advance tax if estimated liability after TDS exceeds ₹10,000. Four installments: 15% by Jun 15, 45% by Sep 15, 75% by Dec 15, 100% by Mar 15. Interest: 234B (1%/month shortfall) + 234C (1%/month deferment).' },
  { slug: 'nri-huf-tax-planning', title: 'NRI HUF Tax Planning', subtitle: 'Save ₹1.2L+ in Taxes Legally', excerpt: 'HUF gets separate PAN + basic exemption. Split income between individual + HUF. How to create, who qualifies, property ownership, 80C/80D for HUF.', category: 'tax', topic: 'income', tags: ['HUF', 'Tax Planning', 'Income Splitting', 'Family'], readTime: '12 min', featured: false, views: '9K+', icon: '👨‍👩‍👧‍👦', color: '#7C3AED', keyNumbers: [{ label: 'Exemption', value: '₹2.5-4L extra' }, { label: 'Saving', value: '₹1.2L+' }, { label: '80C for HUF', value: 'Available' }, { label: 'Karta', value: 'Can be NRI' }], quickAnswer: 'HUF is a separate tax entity with its own PAN and basic exemption (₹2.5L old / ₹4L new regime). NRIs can split rental/investment income between individual + HUF, saving ₹1.2L+ in taxes. Karta can be NRI with NRO account for HUF.' },
  { slug: 'nri-emergency-fund-guide', title: 'NRI Emergency Fund Guide', subtitle: 'How Much, Where & Tax-Efficient', excerpt: 'Dual emergency fund (abroad + India). NRE savings (instant, tax-free) vs liquid MF vs NRE FD. Auto-sweep strategy. Practical allocation model.', category: 'banking', topic: 'banking', tags: ['Emergency Fund', 'Liquid Fund', 'NRE Savings', 'Safety'], readTime: '10 min', featured: false, views: '26K+', icon: '🛟', color: '#059669', keyNumbers: [{ label: 'Abroad', value: '6 months' }, { label: 'India', value: '3-6 months' }, { label: 'Best Option', value: 'NRE Savings' }, { label: 'Auto-Sweep', value: 'FD Rate' }], quickAnswer: 'NRIs need dual emergency funds: 6 months expenses abroad + 3-6 months in India. Best India options: NRE savings (instant, tax-free) → liquid MF (T+1) → NRE FD (tax-free, premature penalty). Use auto-sweep NRE for FD rates with savings liquidity.' },
  { slug: 'nri-reits-invits-guide', title: 'REITs & InvITs for NRIs', subtitle: 'Real Estate & Infra Without Property', excerpt: 'Own commercial real estate and infrastructure via stock exchange. 6-12% yields, ₹300-500 per unit, LTCG 12.5%, vs direct property comparison.', category: 'investment', topic: 'planning', tags: ['REIT', 'InvIT', 'Real Estate Trust', 'Yield'], readTime: '12 min', featured: false, views: '25K+', icon: '🏢', color: '#1D4ED8', keyNumbers: [{ label: 'REIT Yield', value: '6-8%' }, { label: 'InvIT Yield', value: '8-12%' }, { label: 'Min Investment', value: '~₹300' }, { label: 'LTCG', value: '12.5%' }], quickAnswer: 'REITs let NRIs own commercial real estate (Embassy, Mindspace, Brookfield) with 6-8% yields. InvITs offer 8-12% from infrastructure. Buy via PIS demat, min ~₹300/unit. LTCG 12.5% after 12 months. Much better liquidity than physical property.' },
  { slug: 'nri-form-10f-guide', title: 'Form 10F Filing Guide', subtitle: 'Step-by-Step for DTAA Benefits', excerpt: 'Why Form 10F is mandatory, what it captures, step-by-step online filing at incometax.gov.in, submitting to banks, common errors, relationship with TRC.', category: 'compliance', topic: 'filing', tags: ['Form 10F', 'DTAA', 'TRC', 'Online Filing'], readTime: '8 min', featured: false, views: '3K+', icon: '📝', color: '#D97706', keyNumbers: [{ label: 'Mandatory Since', value: 'Oct 2022' }, { label: 'Filing', value: 'Online Only' }, { label: 'With TRC', value: 'Always' }, { label: 'Saves', value: '15-18% TDS' }], quickAnswer: 'Form 10F is mandatory (since Oct 2022, online only) whenever claiming DTAA benefit. It supplements TRC with info most foreign TRCs lack. Without it, banks apply 30% domestic TDS instead of 10-15% treaty rate.' },
  { slug: 'nri-cgas-account-guide', title: 'CGAS Account Guide', subtitle: 'Capital Gains Account Scheme for NRIs', excerpt: 'When to use CGAS (Section 54 claimed but house not bought by ITR date), Type A vs B accounts, which banks offer, opening from abroad via POA.', category: 'tax', topic: 'property', tags: ['CGAS', 'Section 54', 'Capital Gains', 'Deposit'], readTime: '10 min', featured: false, views: '4.5K+', icon: '🏦', color: '#4F46E5', keyNumbers: [{ label: 'Deadline', value: 'ITR due date' }, { label: 'Type A', value: 'Savings' }, { label: 'Type B', value: 'Term Deposit' }, { label: 'Expiry', value: '2/3 years' }], quickAnswer: 'CGAS lets NRIs claim Section 54/54F exemption even before buying the new house — deposit LTCG by ITR due date, then purchase within 2 years (or construct within 3). Available at select nationalized banks. NRIs can open via POA.' },
  { slug: 'nri-compliance-scorecard', title: 'NRI Compliance Scorecard', subtitle: 'Rate Your Compliance 0-100', excerpt: '20-question self-assessment covering tax filing, TDS, banking/FEMA, and investment compliance. Score yourself and get a personalized action plan.', category: 'compliance', topic: 'compliance', tags: ['Scorecard', 'Self-Assessment', 'Compliance Check', 'Action Plan'], readTime: '10 min', featured: false, views: '3.4K+', icon: '✅', color: '#059669', keyNumbers: [{ label: 'Questions', value: '20' }, { label: 'Max Score', value: '100' }, { label: '90-100', value: 'Excellent' }, { label: '<50', value: 'At Risk' }], quickAnswer: '20 questions × 5 points = 100 max. Covers: ITR filing (25 pts), TDS compliance (25 pts), banking/FEMA (25 pts), investment/planning (25 pts). Score 90-100 = excellent, 70-89 = good, 50-69 = needs work, <50 = at risk.' },
  // ── FINAL BATCH (76 total) ──
  { slug: 'nri-beginner-complete-guide', title: 'Just Became an NRI?', subtitle: "Complete Beginner's Guide 2026", excerpt: "Your first 90 days: convert accounts, open NRE, understand what's taxable, start SIPs, get TRC.", category: 'guide', topic: 'filing', tags: ['Beginner', 'New NRI', 'Starter'], readTime: '15 min', featured: true, views: '1.12M+', icon: '🚀', color: '#059669', keyNumbers: [{ label: 'Week 1', value: 'Convert A/C' }, { label: 'Month 1', value: 'Open NRE' }, { label: 'Month 2', value: 'Start SIPs' }, { label: 'Month 3', value: 'Tax Plan' }], quickAnswer: 'Just became NRI? Week 1: convert accounts to NRO. Month 1: open NRE. Month 2: start SIPs. Month 3: understand TDS, submit TRC.' },
  { slug: 'nri-tax-horror-stories', title: '10 NRI Tax Horror Stories', subtitle: 'Real Penalties & Nightmares', excerpt: 'ED raids, FBAR $64K penalties, TDS stuck for 3 years, Section 87A demand notices.', category: 'guide', topic: 'compliance', tags: ['Horror Stories', 'Penalties', 'ED'], readTime: '12 min', featured: true, views: '217K+', icon: '😱', color: '#B91C1C', keyNumbers: [{ label: 'FEMA', value: '₹5L+' }, { label: 'FBAR', value: '$64,545' }, { label: 'TDS Stuck', value: '₹18L' }, { label: 'BMA', value: '₹10L' }], quickAnswer: 'Real stories: Dubai NRI ED penalty, US NRI FBAR fine, UK NRI TDS stuck 3 years. Every story is preventable.' },
  { slug: 'nri-things-banned-restricted', title: '20 Things NRIs Cannot Do', subtitle: 'Restrictions & Prohibitions', excerpt: 'No agri land, no resident account, no ITR-1, no SGBs, no new PPF, no intraday trading.', category: 'compliance', topic: 'compliance', tags: ['Banned', 'Restrictions', 'Prohibited'], readTime: '12 min', featured: false, views: '174K+', icon: '🚫', color: '#DC2626', keyNumbers: [{ label: 'Property', value: 'No Agri' }, { label: 'Banking', value: 'No Res A/C' }, { label: 'Invest', value: 'No SGBs' }, { label: 'Filing', value: 'No ITR-1' }], quickAnswer: 'NRIs cannot: buy agri land, keep resident account, file ITR-1, subscribe SGBs/new PPF, do intraday/F&O.' },
  { slug: 'nri-year-end-tax-planning-march', title: 'Year-End Tax Planning', subtitle: '15 Things Before March 31', excerpt: 'Last-minute: complete 80C, tax-loss harvest, advance tax Mar 15, TRC for next FY.', category: 'tax', topic: 'planning', tags: ['Year-End', 'March 31', 'Last Minute'], readTime: '10 min', featured: false, views: '176K+', icon: '⏰', color: '#E11D48', keyNumbers: [{ label: 'Adv Tax', value: 'Mar 15' }, { label: 'FY Ends', value: 'Mar 31' }, { label: 'LTCG', value: '₹1.25L free' }, { label: 'NRO', value: 'Resets Apr 1' }], quickAnswer: 'Before Mar 31: pay advance tax, complete 80C, harvest LTCG, use NRO limit, verify day count.' },
  { slug: 'nri-banking-15-must-know', title: 'NRI Banking 15 Must-Knows', subtitle: 'Essential Banking Knowledge', excerpt: 'NRE tax-free, FCNR currency shield, auto-sweep trick, NRO cap, joint rules, nominee vs heir.', category: 'banking', topic: 'banking', tags: ['Banking', 'Essentials', 'Auto-Sweep'], readTime: '8 min', featured: false, views: '35K+', icon: '🏦', color: '#0891B2', keyNumbers: [{ label: 'NRE', value: 'Tax-Free' }, { label: 'Sweep', value: 'FD Rate' }, { label: 'NRO', value: 'USD 1M/yr' }, { label: 'Nominee', value: '≠ Heir' }], quickAnswer: 'Convert to NRO in 30 days, NRE = tax-free, FCNR = no forex risk, auto-sweep = FD rates, NRO cap USD 1M/yr.' },
  { slug: 'nri-when-to-exit-indian-market', title: 'When to Exit Indian Market', subtitle: 'Warning Signs & Exit Strategy', excerpt: 'PE >25, FPI outflows, rupee -5%. Partial exit, GIFT City 0% pivot.', category: 'investment', topic: 'planning', tags: ['Exit', 'PE Ratio', 'Contrarian'], readTime: '12 min', featured: false, views: '57K+', icon: '🚪', color: '#B45309', keyNumbers: [{ label: 'PE Warn', value: '>25' }, { label: 'FPI', value: '3mo out' }, { label: 'Tax-Free', value: '₹1.25L/yr' }, { label: 'GIFT', value: '0% Exit' }], quickAnswer: 'Warning: Nifty PE >25, FPI outflows >3 months. Exit: trim 20-30%, stagger 2 FYs, GIFT City pivot for 0% tax.' },
  { slug: 'nri-top-25-questions-answered', title: 'Top 25 NRI Tax Questions', subtitle: 'Expert Answers', excerpt: 'The 25 most-searched questions in 150-200 words each: residency, ITR, NRE, TDS, DTAA, FBAR, FEMA, GIFT City.', category: 'guide', topic: 'filing', tags: ['FAQ', 'Q&A', 'Top Questions'], readTime: '18 min', featured: true, views: '319K+', icon: '❓', color: '#6366F1', keyNumbers: [{ label: 'Questions', value: '25' }, { label: 'Each', value: '150-200w' }, { label: 'Topics', value: 'All NRI' }, { label: 'Format', value: 'AEO' }], quickAnswer: 'Top 25: Am I NRI? File ITR? Which form? NRE taxable? TDS rate? Property tax? Sec 197? 87A? DTAA? FBAR? And 15 more.' },
  { slug: 'nri-ppf-sukanya-samriddhi', title: 'PPF & Sukanya Samriddhi', subtitle: 'NRI Rules & Restrictions', excerpt: 'New PPF: NO. Existing: till maturity. Sukanya: close in 6 months. All small savings NRI rules.', category: 'investment', topic: 'planning', tags: ['PPF', 'Sukanya', 'Small Savings'], readTime: '10 min', featured: false, views: '11K+', icon: '🏛️', color: '#4F46E5', keyNumbers: [{ label: 'New PPF', value: 'NO' }, { label: 'Existing', value: 'Maturity' }, { label: 'SSY', value: 'Close 6mo' }, { label: 'SCSS', value: 'Return Only' }], quickAnswer: 'Cannot open new PPF. Existing till maturity. Sukanya must close within 6 months. NSC/KVP banned. SCSS on return.' },

  // ── VALUE-ADD SPECIALS ──
  { slug: 'nri-spouse-guide-resident-partner', title: 'My Partner is NRI', subtitle: 'Guide for Resident Spouses', excerpt: "Complete guide for the resident spouse managing NRI finances: bank accounts, property, tax filing, investments, insurance, repatriation — everything you need to handle while your partner is abroad.", category: 'guide', topic: 'planning', tags: ['Spouse', 'Resident Partner', 'Family', 'POA'], readTime: '15 min', featured: true, views: 'Unique', icon: '💑', color: '#E11D48', keyNumbers: [{ label: 'Banks', value: 'NRO Joint OK' }, { label: 'Gift', value: 'Tax-Free' }, { label: 'Rent', value: 'Deposit to NRO' }, { label: 'Filing', value: 'Separate ITR' }], quickAnswer: "Resident spouse can hold NRO jointly (not NRE). Money from NRI spouse = tax-free gift. Rental income goes to NRO. File separate ITRs. Use POA to manage investments. Key: keep records of everything." },
  { slug: 'explain-nri-tax-to-parents', title: 'Explain NRI Tax to Parents', subtitle: 'Simple Guide They Will Understand', excerpt: "Written for NRIs to share with parents. Ultra-simple, no jargon: why accounts converted, why TDS is high, what to do with rent, how to handle tax notices, what papers to keep.", category: 'guide', topic: 'planning', tags: ['Parents', 'Simple', 'Family', 'WhatsApp'], readTime: '10 min', featured: true, views: 'Unique', icon: '👨‍👩‍👧', color: '#059669', keyNumbers: [{ label: 'Tone', value: 'Ultra-Simple' }, { label: 'Format', value: 'Conversations' }, { label: 'Bonus', value: 'WhatsApp Forward' }, { label: 'Checklist', value: 'Printable' }], quickAnswer: 'Share this with parents: NRO = Indian money account (30% TDS on FD). NRE = foreign salary account (tax-free). Gift from child = tax-free. Rent goes to NRO. File ITR = get TDS refund. Keep all papers.' },
  { slug: 'nri-letter-templates-pack', title: 'NRI Letter Templates Pack', subtitle: '8 Ready-to-Use Templates', excerpt: "Copy-paste templates: Section 197 application, TRC bank submission, AIS correction, account conversion, FEMA compounding, repatriation request, CA instructions, notice response.", category: 'compliance', topic: 'compliance', tags: ['Templates', 'Letters', 'Section 197', 'Forms'], readTime: '12 min', featured: true, views: 'Unique', icon: '📝', color: '#2563EB', keyNumbers: [{ label: 'Templates', value: '8' }, { label: 'Format', value: 'Copy-Paste' }, { label: 'Covers', value: 'All Key Needs' }, { label: 'Utility', value: 'Highest' }], quickAnswer: '8 ready-to-use templates: Section 197 cover letter, TRC submission to bank, AIS feedback guide, account conversion request, FEMA compounding application, 15CB CA request, repatriation bank letter, 143(1) response.' },
  { slug: 'nri-country-tax-comparison', title: 'NRI Tax by Country', subtitle: 'US vs UK vs UAE vs Canada vs SG vs AU', excerpt: "Massive side-by-side comparison: personal tax rates, DTAA rates, FTC mechanism, foreign reporting, MF treatment, pension, property — all 6 countries on one page.", category: 'guide', topic: 'country', tags: ['Country Comparison', 'US vs UK', 'UAE vs Canada', 'Side-by-Side'], readTime: '16 min', featured: true, views: 'Unique', icon: '🌍', color: '#7C3AED', keyNumbers: [{ label: 'Countries', value: '6' }, { label: 'Parameters', value: '15+' }, { label: 'Scenario', value: 'Same NRI, 6 taxes' }, { label: 'Format', value: 'Tables' }], quickAnswer: 'Same NRI in 6 countries: UAE pays least (no FTC needed, only India tax). US has heaviest compliance (FBAR+FATCA+PFIC). UK balanced. Canada moderate. Singapore favorable. Australia high marginal rates but CGT discount.' },

  // ── ORPHANED CONTENT (previously generated, now indexed) ──
  { slug: 'uk-nri-tax-guide', title: 'UK NRI Tax Guide', subtitle: 'India-UK DTAA, HMRC & Cross-Border', excerpt: 'India-UK DTAA rates, HMRC self-assessment, pension credit method, property CG with FTC, National Insurance.', category: 'guide', topic: 'country', tags: ['UK NRI', 'HMRC', 'India-UK DTAA'], readTime: '14 min', featured: false, views: '2K+', icon: '🇬🇧', color: '#1D4ED8', keyNumbers: [{ label: 'DTAA Interest', value: '15%' }, { label: 'DTAA Dividend', value: '15%' }, { label: 'Pension', value: 'Both tax + credit' }, { label: 'FTC', value: 'Available' }], quickAnswer: 'UK NRIs pay Indian LTCG on property and claim FTC via HMRC self-assessment. DTAA caps interest at 15%. Pension taxable in both countries with credit method.' },
  { slug: 'singapore-nri-tax-guide', title: 'Singapore NRI Tax Guide', subtitle: 'India-Singapore DTAA, CPF & IRAS', excerpt: 'Post-2017 DTAA changes, IRAS reporting, CPF treatment, capital gains now taxable in source country.', category: 'guide', topic: 'country', tags: ['Singapore NRI', 'IRAS', 'CPF'], readTime: '12 min', featured: false, views: '6K+', icon: '🇸🇬', color: '#E11D48', keyNumbers: [{ label: 'DTAA Interest', value: '15%' }, { label: 'CG (post-2017)', value: 'Source country' }, { label: 'FTS', value: '10%' }, { label: 'FTC', value: 'Available' }], quickAnswer: 'Post-2017 amendment removed capital gains exemption. Singapore NRIs now pay Indian CG tax with FTC in Singapore. DTAA interest 15%, FTS 10%.' },
  { slug: 'germany-nri-tax-guide', title: 'Germany NRI Tax Guide', subtitle: 'India-Germany DTAA & Finanzamt', excerpt: 'Most favorable DTAA rates (interest 10%, dividends 10%), Finanzamt reporting, pension exempt in India.', category: 'guide', topic: 'country', tags: ['Germany NRI', 'Finanzamt', 'DTAA 10%'], readTime: '12 min', featured: false, views: '3K+', icon: '🇩🇪', color: '#DC2626', keyNumbers: [{ label: 'DTAA Interest', value: '10%' }, { label: 'DTAA Dividend', value: '10%' }, { label: 'Pension', value: 'Residence only' }, { label: 'FTS', value: '10%' }], quickAnswer: 'Germany has one of the most favorable DTAAs with India. Interest and dividends both at 10%. Pension generally taxable only in residence country.' },
  { slug: 'nri-section-197-lower-tds-guide', title: 'Section 197 Lower TDS Deep Dive', subtitle: 'Application Process & Form 13', excerpt: 'Complete step-by-step for obtaining lower/nil TDS certificate. Form 13 filing, documentation, AO processing, practical examples.', category: 'tax', topic: 'filing', tags: ['Section 197', 'Form 13', 'Lower TDS'], readTime: '12 min', featured: false, views: 'High', icon: '📋', color: '#059669', keyNumbers: [{ label: 'Form', value: 'Form 13' }, { label: 'Timeline', value: '30-45 days' }, { label: 'Savings', value: '₹5-20L' }, { label: 'Portal', value: 'TRACES' }], quickAnswer: 'File Form 13 on TRACES portal with CG computation + exemption proof. AO issues certificate in 30-45 days. Can reduce TDS from 20% to 2-5%.' },
  { slug: 'nri-section-54ec-bonds-guide', title: 'Section 54EC Bonds Deep Dive', subtitle: 'NHAI/REC Bonds for CG Exemption', excerpt: 'Complete guide: ₹50L cap, 6-month deadline, 5-year lock-in, interest taxable, which bonds, application process.', category: 'tax', topic: 'property', tags: ['Section 54EC', 'NHAI Bonds', 'REC Bonds'], readTime: '10 min', featured: false, views: 'High', icon: '📊', color: '#7C3AED', keyNumbers: [{ label: 'Max', value: '₹50L' }, { label: 'Lock-in', value: '5 years' }, { label: 'Deadline', value: '6 months' }, { label: 'Interest', value: '~5.25%' }], quickAnswer: 'Invest up to ₹50L in NHAI/REC bonds within 6 months of property sale. 5-year lock-in, ~5.25% taxable interest. Saves up to ₹6.25L in LTCG tax.' },
  { slug: 'nri-receiving-inheritance-tax', title: 'NRI Receiving Inheritance', subtitle: 'Tax on Inherited Property & Money', excerpt: 'No inheritance tax in India. But capital gains apply on selling inherited property. Cost basis = previous owner. Repatriation of inherited money.', category: 'tax', topic: 'income', tags: ['Inheritance', 'Inherited Property', 'No Inheritance Tax'], readTime: '10 min', featured: false, views: 'High', icon: '🏠', color: '#B45309', keyNumbers: [{ label: 'Inheritance Tax', value: 'ZERO' }, { label: 'CG on Sale', value: 'Yes' }, { label: 'Cost Basis', value: "Previous Owner" }, { label: 'Repatriation', value: 'USD 1M/yr' }], quickAnswer: 'India has no inheritance tax. But selling inherited property triggers capital gains (cost = previous owner cost, holding includes their period). Inherited money repatriable via NRO with Form 15CA/CB.' },
  { slug: 'nri-epf-withdrawal-tax-guide', title: 'NRI EPF Withdrawal Guide', subtitle: 'Process, Tax & TDS', excerpt: 'How NRIs withdraw EPF after leaving India. Online process, TDS rates (30% if <5 years), Form 15G not for NRIs, tax-free if >5 years.', category: 'tax', topic: 'income', tags: ['EPF', 'PF Withdrawal', 'EPFO'], readTime: '10 min', featured: false, views: 'High', icon: '💰', color: '#0891B2', keyNumbers: [{ label: '<5 Years', value: '30% TDS' }, { label: '>5 Years', value: 'Tax-Free' }, { label: 'Form 15G', value: 'NOT for NRI' }, { label: 'Process', value: 'Online' }], quickAnswer: 'NRIs can withdraw full EPF online. Tax-free if service >5 years. If <5 years, TDS at 30% (no Form 15G for NRIs). File ITR to claim refund if actual tax is lower.' },
  { slug: 'nri-15ca-15cb-repatriation-guide', title: 'Form 15CA & 15CB Deep Dive', subtitle: 'Step-by-Step Repatriation Process', excerpt: 'All 4 parts of Form 15CA explained. When 15CB is needed. Step-by-step filing on IT portal. Common bank rejections.', category: 'compliance', topic: 'filing', tags: ['Form 15CA', 'Form 15CB', 'Repatriation'], readTime: '12 min', featured: false, views: 'High', icon: '📝', color: '#6366F1', keyNumbers: [{ label: 'Part A', value: '<₹5L' }, { label: 'Part B', value: 'Non-taxable' }, { label: 'Part C', value: 'With 15CB' }, { label: 'Part D', value: 'Article 5 PE' }], quickAnswer: 'Form 15CA Part A: remittance <₹5L. Part B: not taxable. Part C: taxable, needs 15CB from CA. Part D: Section 195 with PE. File online on incometax.gov.in.' },
  { slug: 'nri-multiple-property-ownership', title: 'NRI Multiple Property Ownership', subtitle: 'Tax on 2+ Properties in India', excerpt: 'Deemed let-out rules, separate CG for each, Section 54 on only one, advance tax, and optimal property portfolio management.', category: 'tax', topic: 'property', tags: ['Multiple Properties', 'Deemed Let-Out', 'Property Portfolio'], readTime: '12 min', featured: false, views: 'High', icon: '🏘️', color: '#B07D3A', keyNumbers: [{ label: 'Self-Occupied', value: '1 only' }, { label: 'Others', value: 'Deemed Let-Out' }, { label: 'Section 54', value: '1 new house' }, { label: 'CG', value: 'Each separate' }], quickAnswer: 'NRIs can own multiple properties but only 1 can be self-occupied (no deemed rent). Others are deemed let-out with notional rental income. Each property sale computed separately for CG.' },
  { slug: 'nri-debt-mutual-fund-tax', title: 'NRI Debt Mutual Fund Tax', subtitle: 'STCG, LTCG & Post-2024 Rules', excerpt: 'Post Finance Act 2024: no indexation for debt MFs. LTCG 12.5% after 24 months. STCG at slab rates. TDS at 30%.', category: 'investment', topic: 'planning', tags: ['Debt MF', 'Post-2024', 'No Indexation'], readTime: '8 min', featured: false, views: 'High', icon: '📊', color: '#4F46E5', keyNumbers: [{ label: 'LTCG', value: '12.5%' }, { label: 'Holding', value: '24 months' }, { label: 'Indexation', value: 'REMOVED' }, { label: 'TDS', value: '30%' }], quickAnswer: 'Post Finance Act 2024: debt MF LTCG at 12.5% after 24 months, NO indexation. STCG at slab rates (up to 30%). AMCs deduct 30% TDS on NRI redemptions.' },
  { slug: 'nri-selling-agricultural-land', title: 'NRI Selling Agricultural Land', subtitle: 'When It Is & Is Not Taxable', excerpt: 'Rural agri land = exempt from CG. Urban agri land = taxable. NRI ownership rules under FEMA. Forced sale timeline.', category: 'tax', topic: 'property', tags: ['Agricultural Land', 'Rural vs Urban', 'Exempt CG'], readTime: '8 min', featured: false, views: 'High', icon: '🌾', color: '#059669', keyNumbers: [{ label: 'Rural', value: 'CG Exempt' }, { label: 'Urban', value: 'Taxable CG' }, { label: 'NRI Can Own?', value: 'Only inherited' }, { label: 'FEMA', value: 'Must sell' }], quickAnswer: 'Rural agricultural land CG is fully exempt. Urban (within municipality) is taxable. NRIs cannot buy agri land but can inherit — must sell within FEMA timeline or get RBI approval.' },
  { slug: 'nri-itr-u-updated-return-guide', title: 'ITR-U Updated Return for NRI', subtitle: 'File After Missing Deadline', excerpt: 'Section 139(8A) allows filing up to 24 months after AY end. 25-50% additional tax. When ITR-U makes sense for NRIs.', category: 'compliance', topic: 'filing', tags: ['ITR-U', 'Updated Return', 'Section 139(8A)'], readTime: '8 min', featured: false, views: 'Niche', icon: '📄', color: '#D97706', keyNumbers: [{ label: 'Window', value: '24 months' }, { label: 'Year 1 Extra', value: '25%' }, { label: 'Year 2 Extra', value: '50%' }, { label: 'Can Claim Refund?', value: 'NO' }], quickAnswer: 'ITR-U lets NRIs file or update returns up to 24 months after AY end. Additional tax: 25% (first year), 50% (second year). Cannot claim refund via ITR-U — only for additional tax payment.' },
  { slug: 'nri-notice-response-guide', title: 'NRI Notice Response Templates', subtitle: 'How to Reply to IT Notices', excerpt: 'Step-by-step responses for 143(1), 143(2), 148, 245, 133(6) notices. E-proceedings from abroad. When to engage CA.', category: 'compliance', topic: 'compliance', tags: ['Notice Response', 'E-Proceedings', 'Templates'], readTime: '10 min', featured: false, views: 'Niche', icon: '⚠️', color: '#B91C1C', keyNumbers: [{ label: '143(1)', value: 'Intimation' }, { label: '143(2)', value: 'Scrutiny' }, { label: '148', value: 'Reassessment' }, { label: 'Response', value: '15-30 days' }], quickAnswer: 'Most NRI notices are 143(1) intimations (automated adjustments). Respond via e-proceedings portal from abroad. For scrutiny (143(2)) or reassessment (148), engage a CA immediately.' },
  { slug: 'nri-closing-bank-accounts-guide', title: 'NRI Closing Bank Accounts', subtitle: 'When Returning or Consolidating', excerpt: 'Process for closing NRE/NRO/FCNR accounts. Converting to resident accounts on return. RFC account for forex. Timing matters.', category: 'banking', topic: 'banking', tags: ['Close Account', 'Return to India', 'RFC'], readTime: '8 min', featured: false, views: 'Niche', icon: '🏦', color: '#0D9488', keyNumbers: [{ label: 'On Return', value: 'Convert to Resident' }, { label: 'RFC', value: 'Keep Forex' }, { label: 'NRE→Savings', value: 'Mandatory' }, { label: 'FCNR', value: 'Mature during RNOR' }], quickAnswer: 'On returning to India: convert NRE/NRO to resident savings (mandatory). Open RFC account to hold foreign currency. Time FCNR maturity during RNOR for tax-free interest.' },
  { slug: 'nri-nre-account-conversion-guide', title: 'NRE Account Conversion Guide', subtitle: 'Resident to NRO & NRO to NRE', excerpt: 'When and how to convert: resident→NRO (on becoming NRI), NRO→NRE (repatriation of sale proceeds), process and documents.', category: 'banking', topic: 'banking', tags: ['Account Conversion', 'NRO to NRE', 'FEMA'], readTime: '8 min', featured: false, views: 'Niche', icon: '🔄', color: '#2563EB', keyNumbers: [{ label: 'Res→NRO', value: 'Mandatory' }, { label: 'NRO→NRE', value: 'After tax' }, { label: 'Timeline', value: '3-7 days' }, { label: 'FEMA', value: 'Required' }], quickAnswer: 'Converting resident to NRO is mandatory on becoming NRI (FEMA). NRO to NRE transfer allowed after paying applicable taxes — submit Form 15CA/15CB + ITR acknowledgment.' },
  { slug: 'nri-foreign-pension-india-tax', title: 'Foreign Pension India Tax', subtitle: 'US 401K, UK State Pension, Aus Super', excerpt: 'How foreign pensions are taxed when NRI returns to India. DTAA treatment by country. 401K, IRA, superannuation rules.', category: 'tax', topic: 'income', tags: ['Foreign Pension', '401K', 'Superannuation', 'UK Pension'], readTime: '10 min', featured: false, views: 'Niche', icon: '🧓', color: '#4F46E5', keyNumbers: [{ label: 'US 401K', value: 'Taxable on withdrawal' }, { label: 'UK State', value: 'DTAA credit' }, { label: 'Aus Super', value: 'Complex' }, { label: 'RNOR', value: 'Exempt' }], quickAnswer: 'Foreign pensions are taxable in India when you become Resident. During RNOR, they remain exempt. US 401K/IRA withdrawals: taxable in both countries with FTC. UK State Pension: DTAA credit method.' },
  { slug: 'nri-reit-invit-guide', title: 'REIT & InvIT NRI Guide (Alt)', subtitle: 'Alternative Real Estate & Infra', excerpt: 'Alternative perspective on REITs and InvITs for NRIs with different taxation breakdown and portfolio allocation approach.', category: 'investment', topic: 'planning', tags: ['REIT', 'InvIT', 'Alternative'], readTime: '10 min', featured: false, views: 'Niche', icon: '🏢', color: '#1D4ED8', keyNumbers: [{ label: 'REIT Yield', value: '6-8%' }, { label: 'InvIT Yield', value: '8-12%' }, { label: 'Min', value: '~₹300' }, { label: 'LTCG', value: '12.5%' }], quickAnswer: 'REITs and InvITs let NRIs invest in commercial real estate and infrastructure with 6-12% yields. Buy via PIS demat. Much better liquidity than direct property.' },
];

// Self-assessment tools
export const ASSESSMENTS = [
  {
    slug: 'residency-check',
    title: 'Am I an NRI?',
    subtitle: 'Residency Status Quick Check',
    description: 'Answer 5 questions to determine your residential status under Indian tax law — NR, RNOR, or Resident.',
    icon: '🛂',
    questions: 5,
    time: '2 min',
  },
  {
    slug: 'property-tax-calculator',
    title: 'Property Sale Tax Calculator',
    subtitle: 'Compare Both Options Instantly',
    description: 'Enter your property details to see capital gains under both 20% indexed and 12.5% flat options. Know your TDS, refund, and best option.',
    icon: '🧮',
    questions: 6,
    time: '3 min',
  },
  {
    slug: 'filing-obligation-check',
    title: 'Do I Need to File ITR?',
    subtitle: 'Filing Obligation Assessment',
    description: 'Quick check based on your Indian income sources to determine if filing is mandatory and which ITR form to use.',
    icon: '📄',
    questions: 4,
    time: '1 min',
  },
  {
    slug: 'old-vs-new-regime',
    title: 'Old vs New Regime Calculator',
    subtitle: 'Which Tax Regime Saves You More?',
    description: 'Enter your income and deductions to compare tax under both regimes. Instant result showing which saves more and by how much.',
    icon: '🔄',
    questions: 5,
    time: '2 min',
  },
  {
    slug: 'tds-refund-estimator',
    title: 'TDS Refund Estimator',
    subtitle: 'How Much Can You Get Back?',
    description: 'Enter your TDS deducted and actual income to estimate your refund. Most NRIs are owed ₹50K-₹5L in excess TDS.',
    icon: '💰',
    questions: 4,
    time: '2 min',
  },
  {
    slug: 'retirement-corpus-calculator',
    title: 'Retirement Corpus Calculator',
    subtitle: 'Can You Retire in India?',
    description: 'Enter your age, savings, and target expenses to find out if your corpus is enough for a comfortable retirement in India.',
    icon: '🏖️',
    questions: 5,
    time: '2 min',
  },
  {
    slug: 'tax-savings-calculator',
    title: 'Tax Savings Calculator',
    subtitle: 'How Much Are You Leaving on the Table?',
    description: 'Enter your NRO interest and TDS to see exactly how much you could save with TRC, ITR filing, and Section 197.',
    icon: '💰',
    questions: 5,
    time: '2 min',
  },
];
