/* ─────────────────────────────────────────────────────────────
   BLOG DATA — NRI Tax Knowledge Hub
   ───────────────────────────────────────────────────────────── */

export const CATEGORIES = [
  { id: 'all', label: 'All', icon: '📚' },
  { id: 'guide', label: 'Guides', icon: '📖' },
  { id: 'tax', label: 'Tax', icon: '💰' },
  { id: 'compliance', label: 'Compliance', icon: '⚖️' },
  { id: 'investment', label: 'Investment', icon: '📈' },
  { id: 'banking', label: 'Banking', icon: '🏦' },
  { id: 'assessment', label: 'Self-Assessment', icon: '✅' },
];

export const BLOGS = [
  {
    slug: 'nri-property-sale-capital-gains',
    title: 'NRI Property Sale & Capital Gains Tax',
    subtitle: 'The Definitive 2026 Guide',
    excerpt: 'Dual tax options (20% indexed vs 12.5% flat), TDS under Section 195, Section 54/54EC exemptions, and complete repatriation guide with Form 15CA/CB.',
    category: 'guide',
    tags: ['Property Sale', 'Capital Gains', 'TDS', 'Section 54'],
    readTime: '15 min',
    featured: true,
    views: '789K+ source views',
    icon: '🏠',
    color: '#2A6B4A',
    keyNumbers: [
      { label: 'CII 2025-26', value: '376' },
      { label: 'LTCG Rate', value: '12.5%' },
      { label: 'TDS Rate', value: '20%' },
      { label: 'Sec 54 Cap', value: '₹10Cr' },
    ],
    quickAnswer: 'When an NRI sells property in India, the buyer deducts TDS at 20% of the entire sale price under Section 195. For pre-July 2024 acquisitions, NRIs choose between 20% with indexation or 12.5% flat rate — whichever gives lower tax.',
  },
  {
    slug: 'nri-tax-filing-itr',
    title: 'NRI Income Tax Filing in India',
    subtitle: 'Complete ITR Guide for AY 2026-27',
    excerpt: 'Step-by-step guide covering ITR form selection, new vs old regime, Section 87A (not for NRIs!), TDS refund claims, AIS reconciliation, and 10 common mistakes.',
    category: 'guide',
    tags: ['ITR Filing', 'Tax Return', 'AY 2026-27', 'New Regime'],
    readTime: '12 min',
    featured: true,
    views: '5.7M+ source views',
    icon: '📋',
    color: '#B07D3A',
    keyNumbers: [
      { label: 'Due Date', value: '31 Jul 2026' },
      { label: 'ITR Form', value: 'ITR-2' },
      { label: 'Exemption', value: '₹4L' },
      { label: 'Sec 87A', value: 'NOT for NRI' },
    ],
    quickAnswer: 'Most NRIs must file ITR-2 in India if income exceeds ₹4 lakh (new regime). The new tax regime is default — NRIs cannot claim Section 87A rebate. Filing is essential to claim TDS refunds, which are often ₹2-5 lakh for property sales.',
  },
  {
    slug: 'nri-tds-rates-refund',
    title: 'TDS on NRI Income in India',
    subtitle: 'Rates, Refund & Section 197 Certificate',
    excerpt: 'Complete TDS rate chart for NRIs — property sale (20%), NRO interest (30%), dividends (20%). How to apply for Section 197 lower TDS certificate and claim refunds.',
    category: 'tax',
    tags: ['TDS', 'Section 195', 'Section 197', 'Refund'],
    readTime: '18 min',
    featured: false,
    views: '1.07M+ source views',
    icon: '🧾',
    color: '#A04848',
    keyNumbers: [
      { label: 'Property TDS', value: '20%' },
      { label: 'NRO Interest', value: '30%' },
      { label: 'Dividend TDS', value: '20%' },
      { label: 'Rent TDS', value: '30%' },
    ],
    quickAnswer: 'NRI TDS rates are significantly higher than resident rates — 30% on NRO interest, 20% on property sale, 20% on dividends. Apply for Section 197 lower TDS certificate to bring deduction in line with actual tax liability.',
  },
  {
    slug: 'nre-nro-fcnr-banking',
    title: 'NRE vs NRO vs FCNR Accounts',
    subtitle: 'NRI Banking Guide 2026',
    excerpt: 'Tax-free NRE interest, NRO taxation at 30%, FCNR currency protection. The 3-account strategy every NRI needs, FEMA conversion rules, and repatriation limits.',
    category: 'banking',
    tags: ['NRE', 'NRO', 'FCNR', 'Banking'],
    readTime: '14 min',
    featured: false,
    views: '3.28M+ source views',
    icon: '🏦',
    color: '#2E5E8C',
    keyNumbers: [
      { label: 'NRE Interest', value: 'Tax-Free' },
      { label: 'NRO TDS', value: '30%' },
      { label: 'Repatriation', value: 'USD 1M/yr' },
      { label: 'FCNR', value: 'FX Protected' },
    ],
    quickAnswer: 'NRE accounts hold foreign earnings with tax-free interest and full repatriation. NRO accounts hold Indian income with 30% TDS and USD 1M/year repatriation limit. FCNR deposits protect against currency risk with tax-free interest.',
  },
  {
    slug: 'dtaa-double-taxation-ftc',
    title: 'DTAA for NRIs',
    subtitle: 'Avoid Double Taxation with Foreign Tax Credit',
    excerpt: 'India\'s treaties with US, UK, UAE, Canada, Singapore, Australia. Country-specific rates, Form 67 (mandatory!), TRC requirements, and practical examples.',
    category: 'tax',
    tags: ['DTAA', 'FTC', 'Form 67', 'TRC'],
    readTime: '16 min',
    featured: false,
    views: '113K+ source views',
    icon: '🌐',
    color: '#5B21B6',
    keyNumbers: [
      { label: 'US Interest', value: '15%' },
      { label: 'UAE Interest', value: '12.5%' },
      { label: 'Form 67', value: 'Mandatory' },
      { label: 'Countries', value: '90+' },
    ],
    quickAnswer: 'India has DTAAs with 90+ countries that cap withholding rates on interest (10-15% vs domestic 20%), dividends, and royalties. Claiming Foreign Tax Credit requires mandatory Form 67 filing before ITR due date — non-filing means FTC denied.',
  },
  {
    slug: 'fema-compliance-nri',
    title: 'FEMA Compliance for NRIs',
    subtitle: 'Rules, Penalties & Common Mistakes',
    excerpt: 'Bank account conversion, property purchase rules, ED penalties (up to 3x), Form 15CA/15CB, LRS limits, and the 2026 Foreign Assets Disclosure Scheme.',
    category: 'compliance',
    tags: ['FEMA', 'RBI', 'Penalties', 'Form 15CA'],
    readTime: '15 min',
    featured: true,
    views: '4.73M+ source views',
    icon: '⚖️',
    color: '#DC2626',
    keyNumbers: [
      { label: 'LRS Limit', value: 'USD 250K' },
      { label: 'NRO Repatriation', value: 'USD 1M' },
      { label: 'ED Penalty', value: 'Up to 3x' },
      { label: 'Disclosure', value: '6-month window' },
    ],
    quickAnswer: 'FEMA violations carry penalties up to 3 times the amount involved. Common violations: keeping resident savings account after becoming NRI, unauthorized property ownership, exceeding LRS limits. Budget 2026 introduced a 6-month disclosure window.',
  },
  {
    slug: 'nri-investment-mutual-funds',
    title: 'NRI Investment in India',
    subtitle: 'Mutual Funds, Stocks & SIP Guide 2026',
    excerpt: 'Equity MF (12.5% LTCG), debt MF, SIP from NRE/NRO, PIS for stocks, GIFT City zero-tax, ESOP lifecycle, crypto 30%, and Budget 2026 changes.',
    category: 'investment',
    tags: ['Mutual Funds', 'Stocks', 'SIP', 'GIFT City'],
    readTime: '18 min',
    featured: false,
    views: '6.42M+ source views',
    icon: '📈',
    color: '#059669',
    keyNumbers: [
      { label: 'Equity LTCG', value: '12.5%' },
      { label: 'STCG', value: '20%' },
      { label: 'GIFT City', value: '0% Tax' },
      { label: 'Crypto', value: '30% Flat' },
    ],
    quickAnswer: 'NRIs can invest in Indian mutual funds via NRE/NRO accounts after KYC. Equity LTCG taxed at 12.5% above ₹1.25L, STCG at 20%. GIFT City funds offer zero-tax alternative. Budget 2026 increased NRI stock holding limit to 10%.',
  },
  {
    slug: 'gift-city-nri-investment',
    title: 'GIFT City for NRIs',
    subtitle: 'Tax-Free Investing in India 2026',
    excerpt: 'Zero capital gains tax, zero STT, zero dividend tax through India\'s International Financial Services Centre. AIF funds, FDs, and NSE IX exchange.',
    category: 'investment',
    tags: ['GIFT City', 'IFSC', 'Zero Tax', 'AIF'],
    readTime: '10 min',
    featured: false,
    views: '63K+ source views',
    icon: '🏛️',
    color: '#7C3AED',
    keyNumbers: [
      { label: 'Capital Gains', value: '0%' },
      { label: 'Dividend Tax', value: '0%' },
      { label: 'STT', value: '0%' },
      { label: 'Min Investment', value: '~USD 150K' },
    ],
    quickAnswer: 'GIFT City IFSC funds offer NRIs zero capital gains tax, zero dividend tax, and zero STT on India investments. Denominated in USD with minimum ~USD 150K. Regulated by IFSCA with strong investor protection.',
  },
  {
    slug: 'nri-rental-income-house-property',
    title: 'NRI Rental Income Tax in India',
    subtitle: 'House Property Guide 2026',
    excerpt: '30% standard deduction, home loan interest (Section 24), deemed let-out property, TDS on rent, loss set-off rules, and municipal tax treatment.',
    category: 'tax',
    tags: ['Rental Income', 'House Property', 'Section 24', 'TDS'],
    readTime: '10 min',
    featured: false,
    views: '386K+ source views',
    icon: '🏢',
    color: '#B45309',
    keyNumbers: [
      { label: 'Std Deduction', value: '30%' },
      { label: 'TDS on Rent', value: '30%' },
      { label: 'Loss Set-off', value: '₹2L' },
      { label: 'Loan Interest', value: 'No Cap (Let-out)' },
    ],
    quickAnswer: 'NRI rental income is taxed after 30% standard deduction. Home loan interest is fully deductible for let-out property (no cap). TDS at 30% is deducted by tenant from the first rupee. Excess TDS is refundable on filing ITR.',
  },
  {
    slug: 'nri-residency-status-determination',
    title: 'NRI Residency Status in India',
    subtitle: 'NR vs RNOR vs Resident 2026',
    excerpt: '182-day rule, modified 60-day rule, RNOR status for returning NRIs, deemed resident provisions (Section 6(1A)), and tax implications of each status.',
    category: 'compliance',
    tags: ['Residency', 'RNOR', 'Section 6', '182 Days'],
    readTime: '8 min',
    featured: false,
    views: '86K+ source views',
    icon: '🌍',
    color: '#0891B2',
    keyNumbers: [
      { label: 'NR Threshold', value: '<182 days' },
      { label: 'Modified Rule', value: '60 days' },
      { label: 'RNOR Period', value: '2-3 years' },
      { label: 'Deemed Trigger', value: '₹15L income' },
    ],
    quickAnswer: 'NRI status requires staying in India less than 182 days (or 60 days with ₹15L+ Indian income). RNOR status gives returning NRIs 2-3 years of protection from global income taxation. Deemed resident provisions apply if not tax resident anywhere.',
  },
  {
    slug: 'nri-budget-2026-changes',
    title: 'Budget 2026 Impact on NRIs',
    subtitle: 'TCS Cut, Property TDS, Foreign Assets',
    excerpt: 'TCS on education/medical cut from 5% to 2%, TAN removed for NRI property TDS, Foreign Assets Disclosure Scheme with reduced penalties and immunity.',
    category: 'tax',
    tags: ['Budget 2026', 'TCS', 'TAN', 'Disclosure'],
    readTime: '8 min',
    featured: false,
    views: '74K+ source views',
    icon: '📜',
    color: '#E11D48',
    keyNumbers: [
      { label: 'TCS Education', value: '2% (was 5%)' },
      { label: 'TAN', value: 'Removed' },
      { label: 'NRI Stock Limit', value: '10%' },
      { label: 'Disclosure', value: '6-month window' },
    ],
    quickAnswer: 'Budget 2026 benefits for NRIs: TCS on education/medical remittance cut from 5% to 2%, TAN no longer needed for property TDS, NRI stock holding limit doubled to 10%, and a 6-month Foreign Assets Disclosure Scheme with immunity.',
  },
  {
    slug: 'nri-retirement-pension-planning',
    title: 'NRI Retirement Planning',
    subtitle: 'Pension, EPF, NPS & Return to India',
    excerpt: 'EPF withdrawal rules, PPF continuation, NPS for NRIs, pension taxation, SWP strategies, and planning for returning to India.',
    category: 'guide',
    tags: ['Retirement', 'Pension', 'EPF', 'NPS'],
    readTime: '12 min',
    featured: false,
    views: '3.86M+ source views',
    icon: '🏖️',
    color: '#4F46E5',
    keyNumbers: [
      { label: 'EPF', value: 'Withdrawable' },
      { label: 'PPF', value: 'Ext. till maturity' },
      { label: 'NPS', value: 'Available' },
      { label: 'SWP', value: 'Tax-efficient' },
    ],
    quickAnswer: 'NRIs can withdraw EPF after leaving India. PPF accounts continue till maturity but cannot accept new deposits. NPS is available to NRIs with tax benefits. Returning NRIs get RNOR status for 2-3 years, protecting foreign income.',
  },
  // ── NEW BATCH ──
  {
    slug: 'us-nri-tax-guide',
    title: 'US NRI Tax Guide',
    subtitle: 'India-US DTAA, FBAR, FATCA & Cross-Border Filing',
    excerpt: 'Complete guide for US-based NRIs: FBAR filing (USD 10K threshold), FATCA Form 8938, PFIC rules for Indian mutual funds, Social Security Totalisation, and India-US DTAA rates.',
    category: 'guide',
    tags: ['US NRI', 'FBAR', 'FATCA', 'PFIC', 'India-US DTAA'],
    readTime: '18 min',
    featured: true,
    views: '2.75M+ source views',
    icon: '🇺🇸',
    color: '#1D4ED8',
    keyNumbers: [
      { label: 'FBAR Threshold', value: 'USD 10K' },
      { label: 'FATCA Threshold', value: 'USD 50K' },
      { label: 'DTAA Interest', value: '15%' },
      { label: 'FBAR Penalty', value: 'USD 12,909+' },
    ],
    quickAnswer: 'US NRIs must file FBAR (FinCEN 114) if aggregate Indian accounts exceed USD 10,000. Indian mutual funds are PFICs requiring Form 8621. India-US DTAA caps interest TDS at 15%. Private pension taxable only in the US.',
  },
  {
    slug: 'nri-esop-rsu-taxation',
    title: 'ESOP & RSU Taxation for NRIs',
    subtitle: 'Complete Cross-Border Guide 2026',
    excerpt: 'Two-stage taxation (perquisite + capital gains), cross-border apportionment, US Section 83(b) election, and practical computation examples.',
    category: 'tax',
    tags: ['ESOP', 'RSU', 'Stock Options', 'Cross-Border'],
    readTime: '15 min',
    featured: false,
    views: '269K+ source views',
    icon: '📊',
    color: '#7C3AED',
    keyNumbers: [
      { label: 'Perquisite', value: 'FMV - Exercise' },
      { label: 'Listed LTCG', value: '12.5%' },
      { label: 'Unlisted LTCG', value: '12.5%' },
      { label: 'Apportionment', value: 'India days/Total' },
    ],
    quickAnswer: 'ESOP/RSU for NRIs is taxed in two stages: perquisite at slab rates (FMV minus exercise price) as salary, then capital gains on sale. Cross-border apportionment applies: only India-service portion is taxable in India.',
  },
  {
    slug: 'nri-tax-saving-strategies',
    title: 'Tax Saving Strategies for NRIs',
    subtitle: 'Deductions & Exemptions Guide 2026',
    excerpt: 'New vs old regime comparison, Section 80C/80D deductions, NRE interest exemption, GIFT City zero-tax route, Section 54/54EC, and Section 197 lower TDS.',
    category: 'tax',
    tags: ['Tax Saving', '80C', '80D', 'Deductions'],
    readTime: '14 min',
    featured: false,
    views: '3.48M+ source views',
    icon: '💡',
    color: '#059669',
    keyNumbers: [
      { label: '80C Limit', value: '₹1.5L' },
      { label: '80D Health', value: '₹25K-₹1L' },
      { label: 'Std Deduction', value: '₹75K' },
      { label: 'NRE Interest', value: 'Tax-Free' },
    ],
    quickAnswer: 'NRIs in the new regime get limited deductions: ₹75K standard deduction (salaried only), 30% on rental income. The biggest saver is NRE interest exemption under Section 10(4). Old regime offers 80C/80D but higher slab rates.',
  },
  {
    slug: 'nri-insurance-guide',
    title: 'NRI Insurance Guide',
    subtitle: 'Life, Health & Tax Benefits in India',
    excerpt: 'Term insurance for NRIs (cheaper in India), health insurance for parents, Section 80C/80D deductions, ULIP taxation, and claim process from abroad.',
    category: 'guide',
    tags: ['Insurance', 'Health', 'Term Plan', 'Section 80D'],
    readTime: '12 min',
    featured: false,
    views: '526K+ source views',
    icon: '🛡️',
    color: '#0891B2',
    keyNumbers: [
      { label: '80C Deduction', value: '₹1.5L' },
      { label: '80D Self', value: '₹25K' },
      { label: '80D Parents', value: '₹50K (60+)' },
      { label: 'ULIP Threshold', value: '₹2.5L' },
    ],
    quickAnswer: 'NRIs can buy term and health insurance in India. Section 80C allows deduction on life insurance premium, 80D on health insurance (₹25K self, ₹50K for senior parents). ULIP maturity is taxable if premium exceeds ₹2.5L/year.',
  },
  {
    slug: 'nri-buying-property-india',
    title: 'NRI Buying Property in India',
    subtitle: 'FEMA, Tax & Legal Guide 2026',
    excerpt: 'What NRIs can buy (no agricultural land), payment rules (NRE/NRO only), home loans, Power of Attorney, TDS obligations, RERA protection, and repatriation.',
    category: 'guide',
    tags: ['Property Purchase', 'FEMA', 'Home Loan', 'POA'],
    readTime: '15 min',
    featured: false,
    views: '345K+ source views',
    icon: '🏗️',
    color: '#B45309',
    keyNumbers: [
      { label: 'Residential', value: 'Allowed' },
      { label: 'Agricultural', value: 'NOT Allowed' },
      { label: 'Payment', value: 'NRE/NRO Only' },
      { label: 'Max Properties', value: '2 (no RBI report)' },
    ],
    quickAnswer: 'NRIs can buy residential and commercial property in India but NOT agricultural land, farmhouse, or plantation. Payment must be from NRE/NRO/FCNR accounts — no cash or foreign currency. Budget 2026 removed TAN requirement for buyers.',
  },
  {
    slug: 'nri-ais-26as-reconciliation',
    title: 'AIS, 26AS & TIS Reconciliation',
    subtitle: 'Avoid Tax Notices — NRI Guide 2026',
    excerpt: 'How the tax department uses AIS to catch mismatches, handling NRE interest in AIS, TDS credit verification, property sale reporting, and the 5-step reconciliation process.',
    category: 'compliance',
    tags: ['AIS', '26AS', 'TIS', 'Reconciliation'],
    readTime: '12 min',
    featured: false,
    views: '853K+ source views',
    icon: '🔍',
    color: '#DC2626',
    keyNumbers: [
      { label: 'SFT Property', value: '>₹30L' },
      { label: 'SFT FD', value: '>₹10L' },
      { label: 'Notice Risk', value: 'High if skip' },
      { label: 'Steps', value: '5-step process' },
    ],
    quickAnswer: 'The Income Tax Department uses AIS as its primary scrutiny tool. NRIs must reconcile AIS, 26AS, and TIS before filing ITR. Common issue: NRE interest appearing as taxable — file feedback to correct it. Mismatches trigger notices under 148/143.',
  },
  {
    slug: 'uae-nri-tax-guide',
    title: 'UAE/Dubai NRI Tax Guide',
    subtitle: 'India-UAE DTAA & Zero-Tax Trap',
    excerpt: 'Why "zero tax" in UAE doesn\'t mean zero Indian tax. DTAA rates (interest 12.5%, dividends 10%), TRC from Federal Tax Authority, and planning for UAE NRIs.',
    category: 'guide',
    tags: ['UAE NRI', 'Dubai', 'Zero Tax', 'India-UAE DTAA'],
    readTime: '14 min',
    featured: false,
    views: '196K+ source views',
    icon: '🇦🇪',
    color: '#047857',
    keyNumbers: [
      { label: 'UAE Tax', value: '0%' },
      { label: 'DTAA Interest', value: '12.5%' },
      { label: 'DTAA Dividend', value: '10%' },
      { label: 'FTC Available', value: 'No (no UAE tax)' },
    ],
    quickAnswer: 'UAE has no personal income tax, but NRIs still owe full Indian tax on Indian income. No FTC is available since there is no UAE tax to credit. India-UAE DTAA reduces interest TDS to 12.5% (from 20%) and dividends to 10%.',
  },
  {
    slug: 'nri-income-tax-notice-response',
    title: 'NRI Income Tax Notice',
    subtitle: 'Types, Response & How to Handle',
    excerpt: 'Why NRIs get more notices, types (143/148/245/133), how to respond from abroad via e-proceedings, when to engage a CA, and common notice triggers.',
    category: 'compliance',
    tags: ['Tax Notice', 'Scrutiny', 'Section 148', 'Appeal'],
    readTime: '14 min',
    featured: false,
    views: '1.23M+ source views',
    icon: '⚠️',
    color: '#B91C1C',
    keyNumbers: [
      { label: 'Response Time', value: '15-30 days' },
      { label: 'Penalty 270A', value: '50-200%' },
      { label: 'Rectification', value: 'Section 154' },
      { label: 'Appeal', value: 'CIT(A) → ITAT' },
    ],
    quickAnswer: 'NRIs receive more notices due to AIS mismatches, non-filing, and high TDS. Common types: 143(1) intimation, 143(2) scrutiny, 148 reassessment. All can be responded to online via e-proceedings — no India visit needed.',
  },
  // ── BATCH 3 ──
  {
    slug: 'nri-returning-to-india',
    title: 'NRI Returning to India',
    subtitle: 'RNOR Status, Tax Planning & Checklist',
    excerpt: 'RNOR qualification (9/10 years NRI), 2-3 year tax-free window on foreign income, FCNR maturity planning, account conversion, and comprehensive return checklist.',
    category: 'guide',
    tags: ['Returning NRI', 'RNOR', 'FCNR', 'Relocation'],
    readTime: '14 min',
    featured: false,
    views: '284K+ source views',
    icon: '🏡',
    color: '#6366F1',
    keyNumbers: [
      { label: 'RNOR Period', value: '2-3 years' },
      { label: 'Foreign Income', value: 'Not Taxed' },
      { label: 'FCNR', value: 'Plan Maturity' },
      { label: 'Account', value: 'Convert to RFC' },
    ],
    quickAnswer: 'Returning NRIs who were NRI in 9 of 10 preceding years qualify for RNOR status for 2-3 years. During RNOR, foreign income is NOT taxable in India — ideal window to mature FCNR deposits and liquidate overseas investments.',
  },
  {
    slug: 'nri-repatriation-guide',
    title: 'NRI Money Repatriation',
    subtitle: 'Form 15CA/CB, Limits & Process',
    excerpt: 'NRE unlimited vs NRO USD 1M cap, Form 15CA (4 parts), Form 15CB CA certificate, property sale repatriation, and common bank rejections.',
    category: 'compliance',
    tags: ['Repatriation', 'Form 15CA', 'Form 15CB', 'FEMA'],
    readTime: '12 min',
    featured: false,
    views: '242K+ source views',
    icon: '💸',
    color: '#0D9488',
    keyNumbers: [
      { label: 'NRE', value: 'Unlimited' },
      { label: 'NRO Cap', value: 'USD 1M/yr' },
      { label: 'Form 15CB', value: 'CA Required' },
      { label: 'Timeline', value: '4-6 weeks' },
    ],
    quickAnswer: 'NRE accounts: unlimited repatriation, no documentation. NRO accounts: capped at USD 1M per FY, requires Form 15CA + Form 15CB from a CA. Property sale proceeds need tax clearance before repatriation. Allow 4-6 weeks.',
  },
  {
    slug: 'nri-aadhaar-pan-oci-guide',
    title: 'Aadhaar, PAN & OCI for NRIs',
    subtitle: 'Complete Document Guide 2026',
    excerpt: 'PAN mandatory for all Indian income, Aadhaar enrollment on visit, OCI card rules, PAN-Aadhaar linking exemption, PAN 2.0, and digital KYC.',
    category: 'compliance',
    tags: ['PAN Card', 'Aadhaar', 'OCI', 'Documents'],
    readTime: '10 min',
    featured: false,
    views: '441K+ source views',
    icon: '🪪',
    color: '#D97706',
    keyNumbers: [
      { label: 'PAN', value: 'Mandatory' },
      { label: 'Aadhaar', value: 'Voluntary' },
      { label: 'OCI Property', value: 'No Agri Land' },
      { label: 'Linking', value: 'NRI Exempt' },
    ],
    quickAnswer: 'PAN is mandatory for all NRIs with Indian income. Aadhaar is voluntary for NRIs but useful for e-verification. NRIs are exempt from PAN-Aadhaar linking if they don\'t have Aadhaar. OCI holders have same tax treatment as NRIs.',
  },
  {
    slug: 'nri-crypto-vda-tax',
    title: 'Crypto & VDA Tax for NRIs',
    subtitle: '30% Flat Rate Complete Guide',
    excerpt: 'Section 115BBH (30% flat), 1% TDS (Section 194S), NO loss set-off, mining/staking/DeFi taxation, and cross-border crypto reporting requirements.',
    category: 'tax',
    tags: ['Crypto', 'VDA', 'Bitcoin', 'Section 115BBH'],
    readTime: '12 min',
    featured: false,
    views: '231K+ source views',
    icon: '₿',
    color: '#F59E0B',
    keyNumbers: [
      { label: 'Tax Rate', value: '30% Flat' },
      { label: 'TDS', value: '1% on Transfer' },
      { label: 'Loss Set-off', value: 'NOT Allowed' },
      { label: 'Deductions', value: 'Cost Only' },
    ],
    quickAnswer: 'Crypto/VDA gains in India are taxed at 30% flat (no slab benefit) under Section 115BBH. 1% TDS applies on transfers. Losses cannot be set off against any income or carried forward. Only cost of acquisition is deductible.',
  },
  {
    slug: 'nri-startup-business-india',
    title: 'NRI Starting Business in India',
    subtitle: 'Company, LLP & Compliance Guide',
    excerpt: 'Pvt Ltd vs LLP comparison, FDI automatic route, incorporation process, FEMA compliance, transfer pricing, GST, and Startup India benefits.',
    category: 'guide',
    tags: ['Startup', 'LLP', 'Company', 'FDI'],
    readTime: '14 min',
    featured: false,
    views: '259K+ source views',
    icon: '🚀',
    color: '#8B5CF6',
    keyNumbers: [
      { label: 'FDI Route', value: 'Automatic' },
      { label: 'Pvt Ltd', value: '2 Directors' },
      { label: 'LLP', value: '2 Partners' },
      { label: 'Startup 80-IAC', value: '3yr Tax Holiday' },
    ],
    quickAnswer: 'NRIs can start Pvt Ltd or LLP in India via FDI automatic route. Investment must come through NRE/NRO/FCNR. Director needs DIN + DSC. Startup India offers 3-year tax holiday under Section 80-IAC for eligible companies.',
  },
  {
    slug: 'nri-home-loan-india',
    title: 'NRI Home Loan in India',
    subtitle: 'Eligibility, Rates & Tax Benefits',
    excerpt: 'LTV 75-80%, interest rates 8.5-9.5%, documents needed, Section 24 interest deduction, Section 80C principal, and repayment from NRE/NRO.',
    category: 'banking',
    tags: ['Home Loan', 'Mortgage', 'Section 24', 'EMI'],
    readTime: '12 min',
    featured: false,
    views: '222K+ source views',
    icon: '🏠',
    color: '#2563EB',
    keyNumbers: [
      { label: 'LTV Ratio', value: '75-80%' },
      { label: 'Interest', value: '8.5-9.5%' },
      { label: 'Sec 24 (Self)', value: '₹2L Cap' },
      { label: 'Sec 24 (Let-out)', value: 'No Cap' },
    ],
    quickAnswer: 'NRIs can get home loans from Indian banks with 75-80% LTV. Interest rates range 8.5-9.5%. Section 24 allows ₹2L interest deduction (self-occupied) or unlimited (let-out). EMI payable from NRE/NRO account.',
  },
  {
    slug: 'canada-nri-tax-guide',
    title: 'Canada NRI Tax Guide',
    subtitle: 'India-Canada DTAA, T1135 & RRSP',
    excerpt: 'India-Canada DTAA rates, T1135 foreign income verification (CAD 100K threshold), RRSP/TFSA treatment, and cross-border property sale planning.',
    category: 'guide',
    tags: ['Canada NRI', 'T1135', 'RRSP', 'India-Canada DTAA'],
    readTime: '14 min',
    featured: false,
    views: '449K+ source views',
    icon: '🇨🇦',
    color: '#DC2626',
    keyNumbers: [
      { label: 'T1135 Threshold', value: 'CAD 100K' },
      { label: 'DTAA Interest', value: '15%' },
      { label: 'DTAA Dividend', value: '15-25%' },
      { label: 'CG Credit', value: 'FTC Available' },
    ],
    quickAnswer: 'Canadian NRIs must file T1135 if foreign assets exceed CAD 100,000. India-Canada DTAA caps interest at 15%. Property sale gains: pay Indian LTCG then claim FTC in Canada. RRSP withdrawals may be taxable in India if resident.',
  },
  {
    slug: 'nri-will-estate-succession',
    title: 'NRI Will & Estate Planning',
    subtitle: 'Succession Laws in India 2026',
    excerpt: 'Why NRIs need a separate Indian will, succession laws, probate process, nominee vs legal heir, cross-border estate planning, and inherited property tax.',
    category: 'guide',
    tags: ['Will', 'Estate', 'Succession', 'Inheritance'],
    readTime: '14 min',
    featured: false,
    views: '24K+ source views',
    icon: '📜',
    color: '#78350F',
    keyNumbers: [
      { label: 'Inheritance Tax', value: 'None in India' },
      { label: 'Probate', value: '3 cities required' },
      { label: 'Nominee', value: '≠ Legal Heir' },
      { label: 'Will Registration', value: 'Recommended' },
    ],
    quickAnswer: 'India has no inheritance tax. NRIs need a separate Indian will for Indian assets. Nominee is custodian, NOT owner — legal heirs inherit. Probate is required in Kolkata, Mumbai, and Chennai. Inherited property CG uses previous owner\'s cost basis.',
  },
];

// Self-assessment tools
export const ASSESSMENTS = [
  {
    slug: 'residency-check',
    title: 'Am I an NRI?',
    subtitle: 'Residency Status Quick Check',
    description: 'Answer 5 questions to determine your residential status under Indian tax law — NR, RNOR, or Resident.',
    icon: '🛂',
    questions: 5,
    time: '2 min',
  },
  {
    slug: 'property-tax-calculator',
    title: 'Property Sale Tax Calculator',
    subtitle: 'Compare Both Options Instantly',
    description: 'Enter your property details to see capital gains under both 20% indexed and 12.5% flat options. Know your TDS, refund, and best option.',
    icon: '🧮',
    questions: 6,
    time: '3 min',
  },
  {
    slug: 'filing-obligation-check',
    title: 'Do I Need to File ITR?',
    subtitle: 'Filing Obligation Assessment',
    description: 'Quick check based on your Indian income sources to determine if filing is mandatory and which ITR form to use.',
    icon: '📄',
    questions: 4,
    time: '1 min',
  },
];
